version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/projects"
  schedule:
    interval: daily
  ignore:
    # For all deps
    - dependency-name: "*"
      # ignore all patch updates
      update-types: ["version-update:semver-patch"]