// DO NOT EDIT MANUALLY! This file was generated by the script "generate_concept_mappings.rb"

using System;
using System.Collections.Generic;

namespace BFDR
{
    /// <summary>Mappings between IJE and FHIR value sets</summary>
    public static class Mappings
    {
        /// <summary>Mappings for BirthAndFetalDeathFinancialClass</summary>
        public static class BirthAndFetalDeathFinancialClass
        {
            /// <summary>IJE -> FHIR Mapping for BirthAndFetalDeathFinancialClass</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "2" },
                { "2", "5" },
                { "3", "81" },
                { "4", "33" },
                { "5", "311" },
                { "6", "38" },
                { "8", "99" },
                { "9", "9999" },
            };
            /// <summary>FHIR -> IJE Mapping for BirthAndFetalDeathFinancialClass</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "2", "1" },
                { "5", "2" },
                { "81", "3" },
                { "33", "4" },
                { "311", "5" },
                { "38", "6" },
                { "99", "8" },
                { "9999", "9" },
            };
        }
        /// <summary>Mappings for BirthAttendantTitles</summary>
        public static class BirthAttendantTitles
        {
            /// <summary>IJE -> FHIR Mapping for BirthAttendantTitles</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "112247003" },
                { "2", "76231001" },
                { "3", "445521000124102" },
                { "4", "445531000124104" },
                { "5", "OTH" },
                { "9", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for BirthAttendantTitles</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "112247003", "1" },
                { "76231001", "2" },
                { "445521000124102", "3" },
                { "445531000124104", "4" },
                { "OTH", "5" },
                { "UNK", "9" },
            };
        }
        /// <summary>Mappings for BirthDeliveryOccurred</summary>
        public static class BirthDeliveryOccurred
        {
            /// <summary>IJE -> FHIR Mapping for BirthDeliveryOccurred</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "22232009" },
                { "2", "91154008" },
                { "3", "408839006" },
                { "4", "408838003" },
                { "6", "67190003" },
                { "5", "unknownplannedhomebirth" },
                { "7", "OTH" },
                { "9", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for BirthDeliveryOccurred</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "22232009", "1" },
                { "91154008", "2" },
                { "408839006", "3" },
                { "408838003", "4" },
                { "67190003", "6" },
                { "unknownplannedhomebirth", "5" },
                { "OTH", "7" },
                { "UNK", "9" },
            };
        }
        /// <summary>Mappings for BirthWeightEditFlags</summary>
        public static class BirthWeightEditFlags
        {
            /// <summary>IJE -> FHIR Mapping for BirthWeightEditFlags</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0off" },
                { "1", "1correctOutOfRange" },
                { "2", "2failedBirthWeightGestationEdit" },
            };
            /// <summary>FHIR -> IJE Mapping for BirthWeightEditFlags</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0off", "0" },
                { "1correctOutOfRange", "1" },
                { "2failedBirthWeightGestationEdit", "2" },
            };
        }
        /// <summary>Mappings for DeliveryRoutes</summary>
        public static class DeliveryRoutes
        {
            /// <summary>IJE -> FHIR Mapping for DeliveryRoutes</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "700000006" },
                { "2", "302383004" },
                { "3", "61586001" },
                { "4", "11466000" },
            };
            /// <summary>FHIR -> IJE Mapping for DeliveryRoutes</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "700000006", "1" },
                { "302383004", "2" },
                { "61586001", "3" },
                { "11466000", "4" },
            };
        }
        /// <summary>Mappings for EstimateOfGestationEditFlags</summary>
        public static class EstimateOfGestationEditFlags
        {
            /// <summary>IJE -> FHIR Mapping for EstimateOfGestationEditFlags</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0off" },
                { "1", "1correctOutOfRange" },
            };
            /// <summary>FHIR -> IJE Mapping for EstimateOfGestationEditFlags</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0off", "0" },
                { "1correctOutOfRange", "1" },
            };
        }
        /// <summary>Mappings for FetalDeathCauseOrCondition</summary>
        public static class FetalDeathCauseOrCondition
        {
            /// <summary>IJE -> FHIR Mapping for FetalDeathCauseOrCondition</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "COD18a1", "44223004" },
                { "COD18a2", "415105001" },
                { "COD18a3", "237292005" },
                { "COD18a4", "270500004" },
                { "COD18a5", "11612004" },
                { "COD18a11", "702709008" },
                { "COD18a12", "277489001" },
                { "COD18a13", "128270001" },
                { "COD18a8", "FCOD_maternalconditions" },
                { "COD18a9", "FCOD_membranes" },
                { "COD18a10", "FCOD_obstetricalcomplications" },
                { "COD18a14", "FCOD_fetalconditions" },
                { "COD18a7", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for FetalDeathCauseOrCondition</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "44223004", "COD18a1" },
                { "415105001", "COD18a2" },
                { "237292005", "COD18a3" },
                { "270500004", "COD18a4" },
                { "11612004", "COD18a5" },
                { "702709008", "COD18a11" },
                { "277489001", "COD18a12" },
                { "128270001", "COD18a13" },
                { "FCOD_maternalconditions", "COD18a8" },
                { "FCOD_membranes", "COD18a9" },
                { "FCOD_obstetricalcomplications", "COD18a10" },
                { "FCOD_fetalconditions", "COD18a14" },
                { "UNK", "COD18a7" },
            };
        }
        /// <summary>Mappings for FetalDeathTimePoints</summary>
        public static class FetalDeathTimePoints
        {
            /// <summary>IJE -> FHIR Mapping for FetalDeathTimePoints</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "N", "434681000124104" },
                { "L", "434671000124102" },
                { "A", "434631000124100" },
                { "U", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for FetalDeathTimePoints</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "434681000124104", "N" },
                { "434671000124102", "L" },
                { "434631000124100", "A" },
                { "UNK", "U" },
            };
        }
        /// <summary>Mappings for FetalPresentation</summary>
        public static class FetalPresentation
        {
            /// <summary>IJE -> FHIR Mapping for FetalPresentation</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "70028003" },
                { "2", "6096002" },
                { "3", "OTH" },
                { "9", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for FetalPresentation</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "70028003", "1" },
                { "6096002", "2" },
                { "OTH", "3" },
                { "UNK", "9" },
            };
        }
        /// <summary>Mappings for InfectionsDuringPregnancyLiveBirth</summary>
        public static class InfectionsDuringPregnancyLiveBirth
        {
            /// <summary>IJE -> FHIR Mapping for InfectionsDuringPregnancyLiveBirth</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "GON", "15628003" },
                { "SYPH", "76272004" },
                { "CHAM", "105629000" },
                { "HEPB", "66071002" },
                { "HEPC", "50711007" },
            };
            /// <summary>FHIR -> IJE Mapping for InfectionsDuringPregnancyLiveBirth</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "15628003", "GON" },
                { "76272004", "SYPH" },
                { "105629000", "CHAM" },
                { "66071002", "HEPB" },
                { "50711007", "HEPC" },
            };
        }
        /// <summary>Mappings for NewbornCongenitalAnomalies</summary>
        public static class NewbornCongenitalAnomalies
        {
            /// <summary>IJE -> FHIR Mapping for NewbornCongenitalAnomalies</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "ANEN", "89369001" },
                { "MNSB", "67531005" },
                { "CCHD", "12770006" },
                { "CDH", "17190001" },
                { "OMPH", "18735004" },
                { "GAST", "72951007" },
                { "LIMB", "67341007" },
                { "CL", "80281008" },
                { "CP", "87979003" },
                { "DOWT", "70156005" },
                { "CDIT", "409709004" },
                { "HYPO", "416010008" },
            };
            /// <summary>FHIR -> IJE Mapping for NewbornCongenitalAnomalies</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "89369001", "ANEN" },
                { "67531005", "MNSB" },
                { "12770006", "CCHD" },
                { "17190001", "CDH" },
                { "18735004", "OMPH" },
                { "72951007", "GAST" },
                { "67341007", "LIMB" },
                { "80281008", "CL" },
                { "87979003", "CP" },
                { "70156005", "DOWT" },
                { "409709004", "CDIT" },
                { "416010008", "HYPO" },
            };
        }
        /// <summary>Mappings for NumberPreviousCesareansEditFlags</summary>
        public static class NumberPreviousCesareansEditFlags
        {
            /// <summary>IJE -> FHIR Mapping for NumberPreviousCesareansEditFlags</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1failedVerified" },
            };
            /// <summary>FHIR -> IJE Mapping for NumberPreviousCesareansEditFlags</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1failedVerified", "1" },
            };
        }
        /// <summary>Mappings for PerformedNotPerformedPlanned</summary>
        public static class PerformedNotPerformedPlanned
        {
            /// <summary>IJE -> FHIR Mapping for PerformedNotPerformedPlanned</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "Y", "398166005" },
                { "N", "262008008" },
                { "P", "397943006" },
            };
            /// <summary>FHIR -> IJE Mapping for PerformedNotPerformedPlanned</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "398166005", "Y" },
                { "262008008", "N" },
                { "397943006", "P" },
            };
        }
        /// <summary>Mappings for PregnancyReportEditFlags</summary>
        public static class PregnancyReportEditFlags
        {
            /// <summary>IJE -> FHIR Mapping for PregnancyReportEditFlags</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
            };
            /// <summary>FHIR -> IJE Mapping for PregnancyReportEditFlags</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
            };
        }
    }
}
