// DO NOT EDIT MANUALLY! This file was generated by the script "scripts/generate_url_strings_from_BFDR_IG.rb"

namespace BFDR
{
    /// <summary>Profile URLs</summary>
    public static class ProfileURL
    {
        /// <summary>URL for BundleDocumentBirthReport</summary>
        public const string BundleDocumentBirthReport = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Bundle-document-birth-report";

        /// <summary>URL for BundleDocumentCodedCauseOfFetalDeath</summary>
        public const string BundleDocumentCodedCauseOfFetalDeath = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Bundle-document-coded-cause-of-fetal-death";

        /// <summary>URL for BundleDocumentCodedIndustryOccupation</summary>
        public const string BundleDocumentCodedIndustryOccupation = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Bundle-document-coded-industry-occupation";

        /// <summary>URL for BundleDocumentDemographicCodedContent</summary>
        public const string BundleDocumentDemographicCodedContent = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Bundle-document-demographic-coded-content";

        /// <summary>URL for BundleDocumentFetalDeathReport</summary>
        public const string BundleDocumentFetalDeathReport = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Bundle-document-fetal-death-report";

        /// <summary>URL for CompositionCodedCauseOfFetalDeath</summary>
        public const string CompositionCodedCauseOfFetalDeath = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Composition-coded-cause-of-fetal-death";

        /// <summary>URL for CompositionCodedIndustryAndOccupation</summary>
        public const string CompositionCodedIndustryAndOccupation = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Composition-coded-industry-and-occupation";

        /// <summary>URL for CompositionCodedRaceAndEthnicity</summary>
        public const string CompositionCodedRaceAndEthnicity = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Composition-coded-race-and-ethnicity";

        /// <summary>URL for CompositionJurisdictionFetalDeathReport</summary>
        public const string CompositionJurisdictionFetalDeathReport = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Composition-jurisdiction-fetal-death-report";

        /// <summary>URL for CompositionJurisdictionLiveBirthReport</summary>
        public const string CompositionJurisdictionLiveBirthReport = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Composition-jurisdiction-live-birth-report";

        /// <summary>URL for CompositionProviderFetalDeathReport</summary>
        public const string CompositionProviderFetalDeathReport = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Composition-provider-fetal-death-report";

        /// <summary>URL for CompositionProviderLiveBirthReport</summary>
        public const string CompositionProviderLiveBirthReport = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Composition-provider-live-birth-report";

        /// <summary>URL for ConditionChorioamnionitis</summary>
        public const string ConditionChorioamnionitis = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-chorioamnionitis";

        /// <summary>URL for ConditionCongenitalAnomalyOfNewborn</summary>
        public const string ConditionCongenitalAnomalyOfNewborn = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-congenital-anomaly-of-newborn";

        /// <summary>URL for ConditionEclampsiaHypertension</summary>
        public const string ConditionEclampsiaHypertension = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-eclampsia-hypertension";

        /// <summary>URL for ConditionFetalDeathInitiatingCauseOrCondition</summary>
        public const string ConditionFetalDeathInitiatingCauseOrCondition = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-fetal-death-initiating-cause-or-condition";

        /// <summary>URL for ConditionFetalDeathOtherCauseOrCondition</summary>
        public const string ConditionFetalDeathOtherCauseOrCondition = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-fetal-death-other-cause-or-condition";

        /// <summary>URL for ConditionGestationalDiabetes</summary>
        public const string ConditionGestationalDiabetes = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-gestational-diabetes";

        /// <summary>URL for ConditionGestationalHypertension</summary>
        public const string ConditionGestationalHypertension = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-gestational-hypertension";

        /// <summary>URL for ConditionInfectionPresentDuringPregnancy</summary>
        public const string ConditionInfectionPresentDuringPregnancy = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-infection-present-during-pregnancy";

        /// <summary>URL for ConditionPerinealLaceration</summary>
        public const string ConditionPerinealLaceration = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-perineal-laceration";

        /// <summary>URL for ConditionPrepregnancyDiabetes</summary>
        public const string ConditionPrepregnancyDiabetes = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-prepregnancy-diabetes";

        /// <summary>URL for ConditionPrepregnancyHypertension</summary>
        public const string ConditionPrepregnancyHypertension = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-prepregnancy-hypertension";

        /// <summary>URL for ConditionRupturedUterus</summary>
        public const string ConditionRupturedUterus = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-ruptured-uterus";

        /// <summary>URL for ConditionSeizure</summary>
        public const string ConditionSeizure = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Condition-seizure";

        /// <summary>URL for CoveragePrincipalPayerDelivery</summary>
        public const string CoveragePrincipalPayerDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Coverage-principal-payer-delivery";

        /// <summary>URL for EncounterBirth</summary>
        public const string EncounterBirth = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Encounter-birth";

        /// <summary>URL for EncounterMaternity</summary>
        public const string EncounterMaternity = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Encounter-maternity";

        /// <summary>URL for ObservationAntibioticsAdministeredDuringLabor</summary>
        public const string ObservationAntibioticsAdministeredDuringLabor = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-antibiotics-administered-during-labor";

        /// <summary>URL for ObservationApgarScore</summary>
        public const string ObservationApgarScore = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-apgar-score";

        /// <summary>URL for ObservationAutopsyHistologicalExamResultsUsed</summary>
        public const string ObservationAutopsyHistologicalExamResultsUsed = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-autopsy-histological-exam-results-used";

        /// <summary>URL for ObservationAutopsyPerformedIndicator</summary>
        public const string ObservationAutopsyPerformedIndicator = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-autopsy-performed-indicator";

        /// <summary>URL for ObservationBirthPluralityOfPregnancy</summary>
        public const string ObservationBirthPluralityOfPregnancy = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-birth-plurality-of-pregnancy";

        /// <summary>URL for ObservationBirthWeight</summary>
        public const string ObservationBirthWeight = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-birth-weight";

        /// <summary>URL for ObservationCigaretteSmokingBeforeDuringPregnancy</summary>
        public const string ObservationCigaretteSmokingBeforeDuringPregnancy = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-cigarette-smoking-before-during-pregnancy";

        /// <summary>URL for ObservationCodedInitiatingFetalDeathCauseOrCondition</summary>
        public const string ObservationCodedInitiatingFetalDeathCauseOrCondition = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-coded-initiating-fetal-death-cause-or-condition";

        /// <summary>URL for ObservationCodedOtherFetalDeathCauseOrCondition</summary>
        public const string ObservationCodedOtherFetalDeathCauseOrCondition = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-coded-other-fetal-death-cause-or-condition";

        /// <summary>URL for ObservationDateOfFirstPrenatalCareVisit</summary>
        public const string ObservationDateOfFirstPrenatalCareVisit = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-date-of-first-prenatal-care-visit";

        /// <summary>URL for ObservationDateOfLastLiveBirth</summary>
        public const string ObservationDateOfLastLiveBirth = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-date-of-last-live-birth";

        /// <summary>URL for ObservationDateOfLastOtherPregnancyOutcome</summary>
        public const string ObservationDateOfLastOtherPregnancyOutcome = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-date-of-last-other-pregnancy-outcome";

        /// <summary>URL for ObservationFetalDeathTimePoint</summary>
        public const string ObservationFetalDeathTimePoint = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-fetal-death-time-point";

        /// <summary>URL for ObservationFetalPresentation</summary>
        public const string ObservationFetalPresentation = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-fetal-presentation";

        /// <summary>URL for ObservationFetalRemainsDispositionMethod</summary>
        public const string ObservationFetalRemainsDispositionMethod = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-fetal-remains-disposition-method";

        /// <summary>URL for ObservationGestationalAgeAtDelivery</summary>
        public const string ObservationGestationalAgeAtDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-gestational-age-at-delivery";

        /// <summary>URL for ObservationHistologicalPlacentalExamPerformed</summary>
        public const string ObservationHistologicalPlacentalExamPerformed = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-histological-placental-exam-performed";

        /// <summary>URL for ObservationICUAdmission</summary>
        public const string ObservationICUAdmission = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-icu-admission";

        /// <summary>URL for ObservationInfantBreastfedAtDischarge</summary>
        public const string ObservationInfantBreastfedAtDischarge = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-infant-breastfed-at-discharge";

        /// <summary>URL for ObservationInfantLiving</summary>
        public const string ObservationInfantLiving = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-infant-living";

        /// <summary>URL for ObservationLaborTrialAttempted</summary>
        public const string ObservationLaborTrialAttempted = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-labor-trial-attempted";

        /// <summary>URL for ObservationLastMenstrualPeriod</summary>
        public const string ObservationLastMenstrualPeriod = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-last-menstrual-period";

        /// <summary>URL for ObservationMotherDeliveryWeight</summary>
        public const string ObservationMotherDeliveryWeight = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-mother-delivery-weight";

        /// <summary>URL for ObservationMotherHeight</summary>
        public const string ObservationMotherHeight = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-mother-height";

        /// <summary>URL for ObservationMotherMarriedDuringPregnancy</summary>
        public const string ObservationMotherMarriedDuringPregnancy = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-mother-married-during-pregnancy";

        /// <summary>URL for ObservationMotherPrepregnancyWeight</summary>
        public const string ObservationMotherPrepregnancyWeight = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-mother-prepregnancy-weight";

        /// <summary>URL for ObservationMotherReceivedWICFood</summary>
        public const string ObservationMotherReceivedWICFood = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-mother-received-wic-food";

        /// <summary>URL for ObservationNICUAdmission</summary>
        public const string ObservationNICUAdmission = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-nicu-admission";

        /// <summary>URL for ObservationNoneOfSpecifiedInfectionsPresentDuringPregnancy</summary>
        public const string ObservationNoneOfSpecifiedInfectionsPresentDuringPregnancy = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-no-infections-present-during-pregnancy";

        /// <summary>URL for ObservationNoneOfSpecifiedCongenitalAnomoliesOfTheNewborn</summary>
        public const string ObservationNoneOfSpecifiedCongenitalAnomoliesOfTheNewborn = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-none-congenital-anomolies-of-the-newborn";

        /// <summary>URL for ObservationNoneOfSpecifiedAbnormalConditionsOfNewborn</summary>
        public const string ObservationNoneOfSpecifiedAbnormalConditionsOfNewborn = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-none-of-specified-abnormal-conditions-of-newborn";

        /// <summary>URL for ObservationNoneOfSpecifiedCharacteristicsOfLaborAndDelivery</summary>
        public const string ObservationNoneOfSpecifiedCharacteristicsOfLaborAndDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-none-of-specified-characteristics-labor-delivery";

        /// <summary>URL for ObservationNoneOfSpecifiedMaternalMorbidities</summary>
        public const string ObservationNoneOfSpecifiedMaternalMorbidities = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-none-of-specified-maternal-morbidities";

        /// <summary>URL for ObservationNoneOfSpecifiedObstetricProcedures</summary>
        public const string ObservationNoneOfSpecifiedObstetricProcedures = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-none-of-specified-obstetric-procedures";

        /// <summary>URL for ObservationNoneOfSpecifiedPregnancyRiskFactors</summary>
        public const string ObservationNoneOfSpecifiedPregnancyRiskFactors = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-none-of-specified-pregnancy-risk-factors";

        /// <summary>URL for ObservationNumberBirthsNowDead</summary>
        public const string ObservationNumberBirthsNowDead = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-number-births-now-dead";

        /// <summary>URL for ObservationNumberBirthsNowLiving</summary>
        public const string ObservationNumberBirthsNowLiving = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-number-births-now-living";

        /// <summary>URL for ObservationNumberFetalDeathsThisDelivery</summary>
        public const string ObservationNumberFetalDeathsThisDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-number-fetal-deaths-this-delivery";

        /// <summary>URL for ObservationNumberLiveBirthsThisDelivery</summary>
        public const string ObservationNumberLiveBirthsThisDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-number-live-births-this-delivery";

        /// <summary>URL for ObservationNumberOtherPregnancyOutcomes</summary>
        public const string ObservationNumberOtherPregnancyOutcomes = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-number-other-pregnancy-outcomes";

        /// <summary>URL for ObservationNumberPrenatalVisits</summary>
        public const string ObservationNumberPrenatalVisits = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-number-prenatal-visits";

        /// <summary>URL for ObservationNumberPreviousCesareans</summary>
        public const string ObservationNumberPreviousCesareans = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-number-previous-cesareans";

        /// <summary>URL for ObservationPaternityAcknowledgementSigned</summary>
        public const string ObservationPaternityAcknowledgementSigned = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-paternity-acknowledgement-signed";

        /// <summary>URL for ObservationPlannedToDeliverAtHome</summary>
        public const string ObservationPlannedToDeliverAtHome = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-planned-to-deliver-at-home";

        /// <summary>URL for ObservationPresentJob</summary>
        public const string ObservationPresentJob = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-present-job";

        /// <summary>URL for ObservationPreviousCesarean</summary>
        public const string ObservationPreviousCesarean = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-previous-cesarean";

        /// <summary>URL for ObservationPreviousPretermBirth</summary>
        public const string ObservationPreviousPretermBirth = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-previous-preterm-birth";

        /// <summary>URL for ObservationSSNRequestedForChild</summary>
        public const string ObservationSSNRequestedForChild = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-ssn-requested-for-child";

        /// <summary>URL for ObservationSteroidsFetalLungMaturation</summary>
        public const string ObservationSteroidsFetalLungMaturation = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-steroids-fetal-lung-maturation";

        /// <summary>URL for ObservationUnknownFinalRouteMethodDelivery</summary>
        public const string ObservationUnknownFinalRouteMethodDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Observation-unknown-final-route-and-method-of-delivery";

        /// <summary>URL for PatientDecedentFetus</summary>
        public const string PatientDecedentFetus = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Patient-decedent-fetus";

        /// <summary>URL for ProcedureAntibioticSuspectedNeonatalSepsis</summary>
        public const string ProcedureAntibioticSuspectedNeonatalSepsis = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-antibiotic-suspected-neonatal-sepsis";

        /// <summary>URL for ProcedureAssistedReproductiveTechnology</summary>
        public const string ProcedureAssistedReproductiveTechnology = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-assisted-reproductive-technology";

        /// <summary>URL for ProcedureAssistedVentilationFollowingDelivery</summary>
        public const string ProcedureAssistedVentilationFollowingDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-assisted-ventilation-following-delivery";

        /// <summary>URL for ProcedureAssistedVentilationMoreThanSixHours</summary>
        public const string ProcedureAssistedVentilationMoreThanSixHours = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-assisted-ventilation-more-than-six-hours";

        /// <summary>URL for ProcedureAugmentationOfLabor</summary>
        public const string ProcedureAugmentationOfLabor = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-augmentation-of-labor";

        /// <summary>URL for ProcedureBloodTransfusion</summary>
        public const string ProcedureBloodTransfusion = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-blood-transfusion";

        /// <summary>URL for ProcedureEpiduralOrSpinalAnesthesia</summary>
        public const string ProcedureEpiduralOrSpinalAnesthesia = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-epidural-or-spinal-anesthesia";

        /// <summary>URL for ProcedureFertilityEnhancingDrugTherapyArtificialInsemination</summary>
        public const string ProcedureFertilityEnhancingDrugTherapyArtificialInsemination = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-fertility-enhancing-drug-therapy-artificial-insem";

        /// <summary>URL for ProcedureFinalRouteMethodDelivery</summary>
        public const string ProcedureFinalRouteMethodDelivery = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-final-route-method-delivery";

        /// <summary>URL for ProcedureInductionOfLabor</summary>
        public const string ProcedureInductionOfLabor = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-induction-of-labor";

        /// <summary>URL for ProcedureInfertilityTreatment</summary>
        public const string ProcedureInfertilityTreatment = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-infertility-treatment";

        /// <summary>URL for ProcedureObstetric</summary>
        public const string ProcedureObstetric = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-obstetric";

        /// <summary>URL for ProcedureSurfactantReplacementTherapy</summary>
        public const string ProcedureSurfactantReplacementTherapy = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-surfactant-replacement-therapy";

        /// <summary>URL for ProcedureUnplannedHysterectomy</summary>
        public const string ProcedureUnplannedHysterectomy = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Procedure-unplanned-hysterectomy";

    }

    /// <summary>Extension URLs</summary>
    public static class ExtensionURL
    {
        /// <summary>URL for ExtensionEncounterMaternityReference</summary>
        public const string ExtensionEncounterMaternityReference = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Extension-encounter-maternity-reference";

        /// <summary>URL for JurisdictionalFacilityIdentifier</summary>
        public const string JurisdictionalFacilityIdentifier = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Extension-jurisdictional-facility-identifier";

        /// <summary>URL for ExtensionRole</summary>
        public const string ExtensionRole = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Extension-role";

        /// <summary>URL for LocationBFDR</summary>
        public const string LocationBFDR = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Location-bfdr";

        /// <summary>URL for PractitionerBirthAttendant</summary>
        public const string PractitionerBirthAttendant = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Practitioner-birth-attendant";

        /// <summary>URL for PractitionerBirthCertifier</summary>
        public const string PractitionerBirthCertifier = "http://hl7.org/fhir/us/bfdr/StructureDefinition/Practitioner-birth-certifier";

        /// <summary>URL for PractitionerRoleBirthAttendant</summary>
        public const string PractitionerRoleBirthAttendant = "http://hl7.org/fhir/us/bfdr/StructureDefinition/practitioner-role-birth-attendant";

        /// <summary>URL for PractitionerRoleBirthCertifier</summary>
        public const string PractitionerRoleBirthCertifier = "http://hl7.org/fhir/us/bfdr/StructureDefinition/practitioner-role-birth-certifier";

        /// <summary>URL for BirthSex</summary>
        public const string BirthSex = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex";

        /// <summary>URL for Plurality (multiple birth total)</summary>
        public const string Plurality = "http://hl7.org/fhir/StructureDefinition/patient-multipleBirthTotal";

        /// <summary>URL for Data Absent Reason</summary>
        public const string DataAbsentReason = "http://hl7.org/fhir/StructureDefinition/data-absent-reason";
    }

    /// <summary>IG URLs</summary>
    public static class IGURL
    {
        /// <summary>URL for BundleDocumentBirthReport</summary>
        public const string BundleDocumentBirthReport = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Bundle-document-birth-report.html";

        /// <summary>URL for BundleDocumentCodedCauseOfFetalDeath</summary>
        public const string BundleDocumentCodedCauseOfFetalDeath = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Bundle-document-coded-cause-of-fetal-death.html";

        /// <summary>URL for BundleDocumentCodedIndustryOccupation</summary>
        public const string BundleDocumentCodedIndustryOccupation = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Bundle-document-coded-industry-occupation.html";

        /// <summary>URL for BundleDocumentDemographicCodedContent</summary>
        public const string BundleDocumentDemographicCodedContent = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Bundle-document-demographic-coded-content.html";

        /// <summary>URL for BundleDocumentFetalDeathReport</summary>
        public const string BundleDocumentFetalDeathReport = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Bundle-document-fetal-death-report.html";

        /// <summary>URL for CompositionCodedCauseOfFetalDeath</summary>
        public const string CompositionCodedCauseOfFetalDeath = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Composition-coded-cause-of-fetal-death.html";

        /// <summary>URL for CompositionCodedIndustryAndOccupation</summary>
        public const string CompositionCodedIndustryAndOccupation = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Composition-coded-industry-and-occupation.html";

        /// <summary>URL for CompositionCodedRaceAndEthnicity</summary>
        public const string CompositionCodedRaceAndEthnicity = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Composition-coded-race-and-ethnicity.html";

        /// <summary>URL for CompositionJurisdictionFetalDeathReport</summary>
        public const string CompositionJurisdictionFetalDeathReport = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Composition-jurisdiction-fetal-death-report.html";

        /// <summary>URL for CompositionJurisdictionLiveBirthReport</summary>
        public const string CompositionJurisdictionLiveBirthReport = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Composition-jurisdiction-live-birth-report.html";

        /// <summary>URL for CompositionProviderFetalDeathReport</summary>
        public const string CompositionProviderFetalDeathReport = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Composition-provider-fetal-death-report.html";

        /// <summary>URL for CompositionProviderLiveBirthReport</summary>
        public const string CompositionProviderLiveBirthReport = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Composition-provider-live-birth-report.html";

        /// <summary>URL for ConditionChorioamnionitis</summary>
        public const string ConditionChorioamnionitis = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-chorioamnionitis.html";

        /// <summary>URL for ConditionCongenitalAnomalyOfNewborn</summary>
        public const string ConditionCongenitalAnomalyOfNewborn = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-congenital-anomaly-of-newborn.html";

        /// <summary>URL for ConditionEclampsiaHypertension</summary>
        public const string ConditionEclampsiaHypertension = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-eclampsia-hypertension.html";

        /// <summary>URL for ConditionFetalDeathInitiatingCauseOrCondition</summary>
        public const string ConditionFetalDeathInitiatingCauseOrCondition = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-fetal-death-initiating-cause-or-condition.html";

        /// <summary>URL for ConditionFetalDeathOtherCauseOrCondition</summary>
        public const string ConditionFetalDeathOtherCauseOrCondition = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-fetal-death-other-cause-or-condition.html";

        /// <summary>URL for ConditionGestationalDiabetes</summary>
        public const string ConditionGestationalDiabetes = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-gestational-diabetes.html";

        /// <summary>URL for ConditionGestationalHypertension</summary>
        public const string ConditionGestationalHypertension = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-gestational-hypertension.html";

        /// <summary>URL for ConditionInfectionPresentDuringPregnancy</summary>
        public const string ConditionInfectionPresentDuringPregnancy = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-infection-present-during-pregnancy.html";

        /// <summary>URL for ConditionPerinealLaceration</summary>
        public const string ConditionPerinealLaceration = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-perineal-laceration.html";

        /// <summary>URL for ConditionPrepregnancyDiabetes</summary>
        public const string ConditionPrepregnancyDiabetes = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-prepregnancy-diabetes.html";

        /// <summary>URL for ConditionPrepregnancyHypertension</summary>
        public const string ConditionPrepregnancyHypertension = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-prepregnancy-hypertension.html";

        /// <summary>URL for ConditionRupturedUterus</summary>
        public const string ConditionRupturedUterus = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-ruptured-uterus.html";

        /// <summary>URL for ConditionSeizure</summary>
        public const string ConditionSeizure = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Condition-seizure.html";

        /// <summary>URL for CoveragePrincipalPayerDelivery</summary>
        public const string CoveragePrincipalPayerDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Coverage-principal-payer-delivery.html";

        /// <summary>URL for EncounterBirth</summary>
        public const string EncounterBirth = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Encounter-birth.html";

        /// <summary>URL for EncounterMaternity</summary>
        public const string EncounterMaternity = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Encounter-maternity.html";

        /// <summary>URL for ExtensionEncounterMaternityReference</summary>
        public const string ExtensionEncounterMaternityReference = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Extension-encounter-maternity-reference.html";

        /// <summary>URL for JurisdictionalFacilityIdentifier</summary>
        public const string JurisdictionalFacilityIdentifier = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Extension-jurisdictional-facility-identifier.html";

        /// <summary>URL for ExtensionRole</summary>
        public const string ExtensionRole = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Extension-role.html";

        /// <summary>URL for LocationBFDR</summary>
        public const string LocationBFDR = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Location-bfdr.html";

        /// <summary>URL for ObservationAntibioticsAdministeredDuringLabor</summary>
        public const string ObservationAntibioticsAdministeredDuringLabor = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-antibiotics-administered-during-labor.html";

        /// <summary>URL for ObservationApgarScore</summary>
        public const string ObservationApgarScore = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-apgar-score.html";

        /// <summary>URL for ObservationAutopsyHistologicalExamResultsUsed</summary>
        public const string ObservationAutopsyHistologicalExamResultsUsed = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-autopsy-histological-exam-results-used.html";

        /// <summary>URL for ObservationAutopsyPerformedIndicator</summary>
        public const string ObservationAutopsyPerformedIndicator = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-autopsy-performed-indicator.html";

        /// <summary>URL for ObservationBirthPluralityOfPregnancy</summary>
        public const string ObservationBirthPluralityOfPregnancy = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-birth-plurality-of-pregnancy.html";

        /// <summary>URL for ObservationBirthWeight</summary>
        public const string ObservationBirthWeight = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-birth-weight.html";

        /// <summary>URL for ObservationCigaretteSmokingBeforeDuringPregnancy</summary>
        public const string ObservationCigaretteSmokingBeforeDuringPregnancy = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-cigarette-smoking-before-during-pregnancy.html";

        /// <summary>URL for ObservationCodedInitiatingFetalDeathCauseOrCondition</summary>
        public const string ObservationCodedInitiatingFetalDeathCauseOrCondition = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-coded-initiating-fetal-death-cause-or-condition.html";

        /// <summary>URL for ObservationCodedOtherFetalDeathCauseOrCondition</summary>
        public const string ObservationCodedOtherFetalDeathCauseOrCondition = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-coded-other-fetal-death-cause-or-condition.html";

        /// <summary>URL for ObservationDateOfFirstPrenatalCareVisit</summary>
        public const string ObservationDateOfFirstPrenatalCareVisit = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-date-of-first-prenatal-care-visit.html";

        /// <summary>URL for ObservationDateOfLastLiveBirth</summary>
        public const string ObservationDateOfLastLiveBirth = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-date-of-last-live-birth.html";

        /// <summary>URL for ObservationDateOfLastOtherPregnancyOutcome</summary>
        public const string ObservationDateOfLastOtherPregnancyOutcome = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-date-of-last-other-pregnancy-outcome.html";

        /// <summary>URL for ObservationFetalDeathTimePoint</summary>
        public const string ObservationFetalDeathTimePoint = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-fetal-death-time-point.html";

        /// <summary>URL for ObservationFetalPresentation</summary>
        public const string ObservationFetalPresentation = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-fetal-presentation.html";

        /// <summary>URL for ObservationFetalRemainsDispositionMethod</summary>
        public const string ObservationFetalRemainsDispositionMethod = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-fetal-remains-disposition-method.html";

        /// <summary>URL for ObservationGestationalAgeAtDelivery</summary>
        public const string ObservationGestationalAgeAtDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-gestational-age-at-delivery.html";

        /// <summary>URL for ObservationHistologicalPlacentalExamPerformed</summary>
        public const string ObservationHistologicalPlacentalExamPerformed = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-histological-placental-exam-performed.html";

        /// <summary>URL for ObservationICUAdmission</summary>
        public const string ObservationICUAdmission = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-icu-admission.html";

        /// <summary>URL for ObservationInfantBreastfedAtDischarge</summary>
        public const string ObservationInfantBreastfedAtDischarge = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-infant-breastfed-at-discharge.html";

        /// <summary>URL for ObservationInfantLiving</summary>
        public const string ObservationInfantLiving = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-infant-living.html";

        /// <summary>URL for ObservationLaborTrialAttempted</summary>
        public const string ObservationLaborTrialAttempted = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-labor-trial-attempted.html";

        /// <summary>URL for ObservationLastMenstrualPeriod</summary>
        public const string ObservationLastMenstrualPeriod = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-last-menstrual-period.html";

        /// <summary>URL for ObservationMotherDeliveryWeight</summary>
        public const string ObservationMotherDeliveryWeight = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-mother-delivery-weight.html";

        /// <summary>URL for ObservationMotherHeight</summary>
        public const string ObservationMotherHeight = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-mother-height.html";

        /// <summary>URL for ObservationMotherMarriedDuringPregnancy</summary>
        public const string ObservationMotherMarriedDuringPregnancy = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-mother-married-during-pregnancy.html";

        /// <summary>URL for ObservationMotherPrepregnancyWeight</summary>
        public const string ObservationMotherPrepregnancyWeight = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-mother-prepregnancy-weight.html";

        /// <summary>URL for ObservationMotherReceivedWICFood</summary>
        public const string ObservationMotherReceivedWICFood = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-mother-received-wic-food.html";

        /// <summary>URL for ObservationNICUAdmission</summary>
        public const string ObservationNICUAdmission = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-nicu-admission.html";

        /// <summary>URL for ObservationNoneOfSpecifiedInfectionsPresentDuringPregnancy</summary>
        public const string ObservationNoneOfSpecifiedInfectionsPresentDuringPregnancy = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-no-infections-present-during-pregnancy.html";

        /// <summary>URL for ObservationNoneOfSpecifiedCongenitalAnomoliesOfTheNewborn</summary>
        public const string ObservationNoneOfSpecifiedCongenitalAnomoliesOfTheNewborn = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-none-congenital-anomolies-of-the-newborn.html";

        /// <summary>URL for ObservationNoneOfSpecifiedAbnormalConditionsOfNewborn</summary>
        public const string ObservationNoneOfSpecifiedAbnormalConditionsOfNewborn = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-none-of-specified-abnormal-conditions-of-newborn.html";

        /// <summary>URL for ObservationNoneOfSpecifiedCharacteristicsOfLaborAndDelivery</summary>
        public const string ObservationNoneOfSpecifiedCharacteristicsOfLaborAndDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-none-of-specified-characteristics-labor-delivery.html";

        /// <summary>URL for ObservationNoneOfSpecifiedMaternalMorbidities</summary>
        public const string ObservationNoneOfSpecifiedMaternalMorbidities = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-none-of-specified-maternal-morbidities.html";

        /// <summary>URL for ObservationNoneOfSpecifiedObstetricProcedures</summary>
        public const string ObservationNoneOfSpecifiedObstetricProcedures = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-none-of-specified-obstetric-procedures.html";

        /// <summary>URL for ObservationNoneOfSpecifiedPregnancyRiskFactors</summary>
        public const string ObservationNoneOfSpecifiedPregnancyRiskFactors = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-none-of-specified-pregnancy-risk-factors.html";

        /// <summary>URL for ObservationNumberBirthsNowDead</summary>
        public const string ObservationNumberBirthsNowDead = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-number-births-now-dead.html";

        /// <summary>URL for ObservationNumberBirthsNowLiving</summary>
        public const string ObservationNumberBirthsNowLiving = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-number-births-now-living.html";

        /// <summary>URL for ObservationNumberFetalDeathsThisDelivery</summary>
        public const string ObservationNumberFetalDeathsThisDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-number-fetal-deaths-this-delivery.html";

        /// <summary>URL for ObservationNumberLiveBirthsThisDelivery</summary>
        public const string ObservationNumberLiveBirthsThisDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-number-live-births-this-delivery.html";

        /// <summary>URL for ObservationNumberOtherPregnancyOutcomes</summary>
        public const string ObservationNumberOtherPregnancyOutcomes = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-number-other-pregnancy-outcomes.html";

        /// <summary>URL for ObservationNumberPrenatalVisits</summary>
        public const string ObservationNumberPrenatalVisits = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-number-prenatal-visits.html";

        /// <summary>URL for ObservationNumberPreviousCesareans</summary>
        public const string ObservationNumberPreviousCesareans = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-number-previous-cesareans.html";

        /// <summary>URL for ObservationPaternityAcknowledgementSigned</summary>
        public const string ObservationPaternityAcknowledgementSigned = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-paternity-acknowledgement-signed.html";

        /// <summary>URL for ObservationPlannedToDeliverAtHome</summary>
        public const string ObservationPlannedToDeliverAtHome = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-planned-to-deliver-at-home.html";

        /// <summary>URL for ObservationPresentJob</summary>
        public const string ObservationPresentJob = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-present-job.html";

        /// <summary>URL for ObservationPreviousCesarean</summary>
        public const string ObservationPreviousCesarean = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-previous-cesarean.html";

        /// <summary>URL for ObservationPreviousPretermBirth</summary>
        public const string ObservationPreviousPretermBirth = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-previous-preterm-birth.html";

        /// <summary>URL for ObservationSSNRequestedForChild</summary>
        public const string ObservationSSNRequestedForChild = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-ssn-requested-for-child.html";

        /// <summary>URL for ObservationSteroidsFetalLungMaturation</summary>
        public const string ObservationSteroidsFetalLungMaturation = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-steroids-fetal-lung-maturation.html";

        /// <summary>URL for ObservationUnknownFinalRouteMethodDelivery</summary>
        public const string ObservationUnknownFinalRouteMethodDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Observation-unknown-final-route-and-method-of-delivery.html";

        /// <summary>URL for PatientDecedentFetus</summary>
        public const string PatientDecedentFetus = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Patient-decedent-fetus.html";

        /// <summary>URL for PractitionerBirthAttendant</summary>
        public const string PractitionerBirthAttendant = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Practitioner-birth-attendant.html";

        /// <summary>URL for PractitionerBirthCertifier</summary>
        public const string PractitionerBirthCertifier = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Practitioner-birth-certifier.html";

        /// <summary>URL for ProcedureAntibioticSuspectedNeonatalSepsis</summary>
        public const string ProcedureAntibioticSuspectedNeonatalSepsis = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-antibiotic-suspected-neonatal-sepsis.html";

        /// <summary>URL for ProcedureAssistedReproductiveTechnology</summary>
        public const string ProcedureAssistedReproductiveTechnology = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-assisted-reproductive-technology.html";

        /// <summary>URL for ProcedureAssistedVentilationFollowingDelivery</summary>
        public const string ProcedureAssistedVentilationFollowingDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-assisted-ventilation-following-delivery.html";

        /// <summary>URL for ProcedureAssistedVentilationMoreThanSixHours</summary>
        public const string ProcedureAssistedVentilationMoreThanSixHours = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-assisted-ventilation-more-than-six-hours.html";

        /// <summary>URL for ProcedureAugmentationOfLabor</summary>
        public const string ProcedureAugmentationOfLabor = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-augmentation-of-labor.html";

        /// <summary>URL for ProcedureBloodTransfusion</summary>
        public const string ProcedureBloodTransfusion = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-blood-transfusion.html";

        /// <summary>URL for ProcedureEpiduralOrSpinalAnesthesia</summary>
        public const string ProcedureEpiduralOrSpinalAnesthesia = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-epidural-or-spinal-anesthesia.html";

        /// <summary>URL for ProcedureFertilityEnhancingDrugTherapyArtificialInsemination</summary>
        public const string ProcedureFertilityEnhancingDrugTherapyArtificialInsemination = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-fertility-enhancing-drug-therapy-artificial-insem.html";

        /// <summary>URL for ProcedureFinalRouteMethodDelivery</summary>
        public const string ProcedureFinalRouteMethodDelivery = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-final-route-method-delivery.html";

        /// <summary>URL for ProcedureInductionOfLabor</summary>
        public const string ProcedureInductionOfLabor = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-induction-of-labor.html";

        /// <summary>URL for ProcedureInfertilityTreatment</summary>
        public const string ProcedureInfertilityTreatment = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-infertility-treatment.html";

        /// <summary>URL for ProcedureObstetric</summary>
        public const string ProcedureObstetric = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-obstetric.html";

        /// <summary>URL for ProcedureSurfactantReplacementTherapy</summary>
        public const string ProcedureSurfactantReplacementTherapy = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-surfactant-replacement-therapy.html";

        /// <summary>URL for ProcedureUnplannedHysterectomy</summary>
        public const string ProcedureUnplannedHysterectomy = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-Procedure-unplanned-hysterectomy.html";

        /// <summary>URL for PractitionerRoleBirthAttendant</summary>
        public const string PractitionerRoleBirthAttendant = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-practitioner-role-birth-attendant.html";

        /// <summary>URL for PractitionerRoleBirthCertifier</summary>
        public const string PractitionerRoleBirthCertifier = "http://build.fhir.org/ig/HL7/bfdr/StructureDefinition-practitioner-role-birth-certifier.html";

    }

    /// <summary>BFDR Custom Code System URLs</summary>
    public static class CodeSystemURL
    {
        /// <summary> Local BFDR Codes </summary>
        public const string LocalBFDRCodes = "http://hl7.org/fhir/us/bfdr/CodeSystem/CodeSystem-local-bfdr-codes";
    }

}
