
// TODO: DO NOT EDIT MANUALLY! This file was generated by the script "tools/generate_value_set_lookups_from_VRDR_IG.rb"

namespace BFDR
{
    /// <summary> ValueSet Helpers </summary>
    public static class ValueSets
    {
        /// <summary> BirthSex </summary>
        public static class BirthSex {

            // TODO: These are the current mappings in the IG, these need to be changed to a 1-1 relationship from IJE to FHIR
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "M", "Male", VR.CodeSystems.AdministrativeGender },
                { "F", "Female", VR.CodeSystems.AdministrativeGender },
                { "UNK", "unknown", VR.CodeSystems.NullFlavor_HL7_V3},
                { "ASKU", "asked but unknown", VR.CodeSystems.NullFlavor_HL7_V3},
                { "UNK", "other", VR.CodeSystems.NullFlavor_HL7_V3}
            };
            /// <summary> Male </summary>
            public static string  Male = "M";
            /// <summary> Female </summary>
            public static string  Female = "F";
            /// <summary> Asked but Unknown </summary>
            public static string  AskedButUnknown = "ASKU";
            /// <summary> Other </summary>
            public static string  Other = "OTH";
            /// <summary> Unknown </summary>
            public static string  Unknown = "UNK";

        };
    }
}