// DO NOT EDIT MANUALLY! This file was generated by the script "generate_value_set_lookups.rb"

namespace BFDR
{
    /// <summary> ValueSet Helpers </summary>
    public static class ValueSets
    {
        /// <summary> ApgarTiming </summary>
        public static class ApgarTiming {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "9272-6", "1 minute Apgar Score", VR.CodeSystems.LOINC },
                { "9274-2", "5 minute Apgar Score", VR.CodeSystems.LOINC },
                { "9271-8", "10 minute Apgar Score", VR.CodeSystems.LOINC },
                { "443848000", "Apgar score at 15 minutes (observable entity)", VR.CodeSystems.SCT },
                { "443849008", "Apgar score at 20 minutes (observable entity)", VR.CodeSystems.SCT },
            };

            /// <summary> _1_Minute_Apgar_Score </summary>
            public static string _1_Minute_Apgar_Score = "9272-6";
            /// <summary> _5_Minute_Apgar_Score </summary>
            public static string _5_Minute_Apgar_Score = "9274-2";
            /// <summary> _10_Minute_Apgar_Score </summary>
            public static string _10_Minute_Apgar_Score = "9271-8";
            /// <summary> Apgar_Score_At_15_Minutes_Observable_Entity </summary>
            public static string Apgar_Score_At_15_Minutes_Observable_Entity = "443848000";
            /// <summary> Apgar_Score_At_20_Minutes_Observable_Entity </summary>
            public static string Apgar_Score_At_20_Minutes_Observable_Entity = "443849008";
        };

        /// <summary> BirthAndFetalDeathFinancialClass </summary>
        public static class BirthAndFetalDeathFinancialClass {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "33", "Indian Health Service or Tribe", VR.CodeSystems.NAHDO },
                { "2", "MEDICAID", VR.CodeSystems.NAHDO },
                { "99", "No Typology Code available for payment source", VR.CodeSystems.NAHDO },
                { "38", "Other Government (Federal, State, Local not specified)", VR.CodeSystems.NAHDO },
                { "5", "PRIVATE HEALTH INSURANCE", VR.CodeSystems.NAHDO },
                { "81", "Self-pay", VR.CodeSystems.NAHDO },
                { "311", "TRICARE (CHAMPUS)", VR.CodeSystems.NAHDO },
                { "9999", "Unavailable / Unknown", VR.CodeSystems.NAHDO },
            };

            /// <summary> Indian_Health_Service_Or_Tribe </summary>
            public static string Indian_Health_Service_Or_Tribe = "33";
            /// <summary> Medicaid </summary>
            public static string Medicaid = "2";
            /// <summary> No_Typology_Code_Available_For_Payment_Source </summary>
            public static string No_Typology_Code_Available_For_Payment_Source = "99";
            /// <summary> Other_Government_Federal_State_Local_Not_Specified </summary>
            public static string Other_Government_Federal_State_Local_Not_Specified = "38";
            /// <summary> Private_Health_Insurance </summary>
            public static string Private_Health_Insurance = "5";
            /// <summary> Self_Pay </summary>
            public static string Self_Pay = "81";
            /// <summary> Tricare_Champus </summary>
            public static string Tricare_Champus = "311";
            /// <summary> Unavailable_Unknown </summary>
            public static string Unavailable_Unknown = "9999";
        };

        /// <summary> BirthAttendantTitles </summary>
        public static class BirthAttendantTitles {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "112247003", "Medical Doctor", VR.CodeSystems.SCT },
                { "76231001", "Osteopath", VR.CodeSystems.SCT },
                { "445521000124102", "Advanced Practice Midwife", VR.CodeSystems.SCT },
                { "445531000124104", "Lay Midwife", VR.CodeSystems.SCT },
                { "OTH", "Other", VR.CodeSystems.NullFlavor_HL7_V3 },
                { "UNK", "Unknown", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Medical_Doctor </summary>
            public static string Medical_Doctor = "112247003";
            /// <summary> Osteopath </summary>
            public static string Osteopath = "76231001";
            /// <summary> Advanced_Practice_Midwife </summary>
            public static string Advanced_Practice_Midwife = "445521000124102";
            /// <summary> Lay_Midwife </summary>
            public static string Lay_Midwife = "445531000124104";
            /// <summary> Other </summary>
            public static string Other = "OTH";
            /// <summary> Unknown </summary>
            public static string Unknown = "UNK";
        };

        /// <summary> BirthDeliveryOccurred </summary>
        public static class BirthDeliveryOccurred {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "22232009", "Hospital", VR.CodeSystems.SCT },
                { "91154008", "Free-standing birthing center", VR.CodeSystems.SCT },
                { "408839006", "Planned home birth", VR.CodeSystems.SCT },
                { "408838003", "Unplanned home birth", VR.CodeSystems.SCT },
                { "67190003", "Free-standing clinic", VR.CodeSystems.SCT },
                { "unknownplannedhomebirth", "Unknown if Planned Home Birth", VR.CodeSystems.LocalBFDRCodes },
                { "OTH", "Other", VR.CodeSystems.NullFlavor_HL7_V3 },
                { "UNK", "Unknown", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Hospital </summary>
            public static string Hospital = "22232009";
            /// <summary> Free_Standing_Birthing_Center </summary>
            public static string Free_Standing_Birthing_Center = "91154008";
            /// <summary> Planned_Home_Birth </summary>
            public static string Planned_Home_Birth = "408839006";
            /// <summary> Unplanned_Home_Birth </summary>
            public static string Unplanned_Home_Birth = "408838003";
            /// <summary> Free_Standing_Clinic </summary>
            public static string Free_Standing_Clinic = "67190003";
            /// <summary> Unknown_If_Planned_Home_Birth </summary>
            public static string Unknown_If_Planned_Home_Birth = "unknownplannedhomebirth";
            /// <summary> Other </summary>
            public static string Other = "OTH";
            /// <summary> Unknown </summary>
            public static string Unknown = "UNK";
        }

        /// <summary> BirthWeightEditFlags </summary>
        public static class BirthWeightEditFlags {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "0off", "Off", VR.CodeSystems.VRCLEditFlags },
                { "1correctOutOfRange", "Queried data correct, out of range", VR.CodeSystems.BFDREditFlags },
                { "2failedBirthWeightGestationEdit", "Queried, failed birthweight/gestation edit", VR.CodeSystems.BFDREditFlags },
            };

            /// <summary> Off </summary>
            public static string Off = "0off";
            /// <summary> Queried_Data_Correct_Out_Of_Range </summary>
            public static string Queried_Data_Correct_Out_Of_Range = "1correctOutOfRange";
            /// <summary> Queried_Failed_Birthweight_Gestation_Edit </summary>
            public static string Queried_Failed_Birthweight_Gestation_Edit = "2failedBirthWeightGestationEdit";
        };

        /// <summary> DeliveryRoutes </summary>
        public static class DeliveryRoutes {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "700000006", "Vaginal delivery of fetus (procedure)", VR.CodeSystems.SCT },
                { "302383004", "Forceps delivery (procedure)", VR.CodeSystems.SCT },
                { "61586001", "Delivery by vacuum extraction (procedure)", VR.CodeSystems.SCT },
                { "11466000", "Cesarean section (procedure)", VR.CodeSystems.SCT },
            };

            /// <summary> Vaginal_Delivery_Of_Fetus_Procedure </summary>
            public static string Vaginal_Delivery_Of_Fetus_Procedure = "700000006";
            /// <summary> Forceps_Delivery_Procedure </summary>
            public static string Forceps_Delivery_Procedure = "302383004";
            /// <summary> Delivery_By_Vacuum_Extraction_Procedure </summary>
            public static string Delivery_By_Vacuum_Extraction_Procedure = "61586001";
            /// <summary> Cesarean_Section_Procedure </summary>
            public static string Cesarean_Section_Procedure = "11466000";
        };

        /// <summary> EstimateOfGestationEditFlags </summary>
        public static class EstimateOfGestationEditFlags {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "0off", "Off", VR.CodeSystems.VRCLEditFlags },
                { "1correctOutOfRange", "Queried data correct, out of range", VR.CodeSystems.BFDREditFlags },
            };

            /// <summary> Off </summary>
            public static string Off = "0off";
            /// <summary> Queried_Data_Correct_Out_Of_Range </summary>
            public static string Queried_Data_Correct_Out_Of_Range = "1correctOutOfRange";
        };

        /// <summary> FetalDeathCauseOrCondition </summary>
        public static class FetalDeathCauseOrCondition {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "44223004", "Premature rupture of membranes (disorder)", VR.CodeSystems.SCT },
                { "415105001", "Placental abruption (disorder)", VR.CodeSystems.SCT },
                { "237292005", "Placental insufficiency (disorder)", VR.CodeSystems.SCT },
                { "270500004", "Prolapsed cord (disorder)", VR.CodeSystems.SCT },
                { "11612004", "Chorioamnionitis (disorder)", VR.CodeSystems.SCT },
                { "702709008", "Congenital anomaly of fetus (Specify) (disorder)", VR.CodeSystems.SCT },
                { "277489001", "Fetal trauma (Specify) (disorder)", VR.CodeSystems.SCT },
                { "128270001", "Infectious disorder of the fetus (Specify) (disorder)", VR.CodeSystems.SCT },
                { "FCOD_maternalconditions", "Maternal Conditions/Diseases (Specify)(disorder)", VR.CodeSystems.LocalBFDRCodes },
                { "FCOD_membranes", "Complications of Placenta, Cord, or Membranes: Other (Specify)(disorder)", VR.CodeSystems.LocalBFDRCodes },
                { "FCOD_obstetricalcomplications", "Other Obstetrical or Pregnancy Complications (Specify)(disorder)", VR.CodeSystems.LocalBFDRCodes },
                { "FCOD_fetalconditions", "Other Fetal Conditions/Disorder (Specify)(disorder)", VR.CodeSystems.LocalBFDRCodes },
                { "UNK", "unknown", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Premature_Rupture_Of_Membranes_Disorder </summary>
            public static string Premature_Rupture_Of_Membranes_Disorder = "44223004";
            /// <summary> Placental_Abruption_Disorder </summary>
            public static string Placental_Abruption_Disorder = "415105001";
            /// <summary> Placental_Insufficiency_Disorder </summary>
            public static string Placental_Insufficiency_Disorder = "237292005";
            /// <summary> Prolapsed_Cord_Disorder </summary>
            public static string Prolapsed_Cord_Disorder = "270500004";
            /// <summary> Chorioamnionitis_Disorder </summary>
            public static string Chorioamnionitis_Disorder = "11612004";
            /// <summary> Congenital_Anomaly_Of_Fetus_Specify_Disorder </summary>
            public static string Congenital_Anomaly_Of_Fetus_Specify_Disorder = "702709008";
            /// <summary> Fetal_Trauma_Specify_Disorder </summary>
            public static string Fetal_Trauma_Specify_Disorder = "277489001";
            /// <summary> Infectious_Disorder_Of_The_Fetus_Specify_Disorder </summary>
            public static string Infectious_Disorder_Of_The_Fetus_Specify_Disorder = "128270001";
            /// <summary> Maternal_Conditions_Diseases_Specify_Disorder </summary>
            public static string Maternal_Conditions_Diseases_Specify_Disorder = "FCOD_maternalconditions";
            /// <summary> Complications_Of_Placenta_Cord_Or_Membranes_Other_Specify_Disorder </summary>
            public static string Complications_Of_Placenta_Cord_Or_Membranes_Other_Specify_Disorder = "FCOD_membranes";
            /// <summary> Other_Obstetrical_Or_Pregnancy_Complications_Specify_Disorder </summary>
            public static string Other_Obstetrical_Or_Pregnancy_Complications_Specify_Disorder = "FCOD_obstetricalcomplications";
            /// <summary> Other_Fetal_Conditions_Disorder_Specify_Disorder </summary>
            public static string Other_Fetal_Conditions_Disorder_Specify_Disorder = "FCOD_fetalconditions";
            /// <summary> Unknown </summary>
            public static string Unknown = "UNK";
        };

        /// <summary> FetalDeathTimePoints </summary>
        public static class FetalDeathTimePoints {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "434681000124104", "Antepartum fetal death with cessation of labor", VR.CodeSystems.SCT },
                { "434671000124102", "Antepartum fetal death with continued labor", VR.CodeSystems.SCT },
                { "434631000124100", "Fetal intrapartum death after first assessment", VR.CodeSystems.SCT },
                { "UNK", "Unknown", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Antepartum_Fetal_Death_With_Cessation_Of_Labor </summary>
            public static string Antepartum_Fetal_Death_With_Cessation_Of_Labor = "434681000124104";
            /// <summary> Antepartum_Fetal_Death_With_Continued_Labor </summary>
            public static string Antepartum_Fetal_Death_With_Continued_Labor = "434671000124102";
            /// <summary> Fetal_Intrapartum_Death_After_First_Assessment </summary>
            public static string Fetal_Intrapartum_Death_After_First_Assessment = "434631000124100";
            /// <summary> Unknown </summary>
            public static string Unknown = "UNK";
        };

        /// <summary> FetalPresentations </summary>
        public static class FetalPresentations {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "70028003", "Vertex presentation (finding)", VR.CodeSystems.SCT },
                { "6096002", "Breech presentation (finding)", VR.CodeSystems.SCT },
                { "163518000", "On examination - fetal presentation unsure	Unknown fetal presentation (finding)", VR.CodeSystems.SCT },
                { "OTH", "Other", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Vertex_Presentation_Finding </summary>
            public static string Vertex_Presentation_Finding = "70028003";
            /// <summary> Breech_Presentation_Finding </summary>
            public static string Breech_Presentation_Finding = "6096002";
            /// <summary> On_Examination_Fetal_Presentation_Unsure_Unknown_Fetal_Presentation_Finding </summary>
            public static string On_Examination_Fetal_Presentation_Unsure_Unknown_Fetal_Presentation_Finding = "163518000";
            /// <summary> Other </summary>
            public static string Other = "OTH";
        };

        /// <summary> FetalRemainsDispositionMethod </summary>
        public static class FetalRemainsDispositionMethod {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "449971000124106", "Burial", VR.CodeSystems.SCT },
                { "449961000124104", "Cremation", VR.CodeSystems.SCT },
                { "449951000124101", "Donation", VR.CodeSystems.SCT },
                { "455401000124109", "Hospital Disposition", VR.CodeSystems.SCT },
                { "449941000124103", "Removal from state", VR.CodeSystems.SCT },
                { "OTH", "Other", VR.CodeSystems.NullFlavor_HL7_V3 },
                { "UNK", "Unknown", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Burial </summary>
            public static string Burial = "449971000124106";
            /// <summary> Cremation </summary>
            public static string Cremation = "449961000124104";
            /// <summary> Donation </summary>
            public static string Donation = "449951000124101";
            /// <summary> Hospital_Disposition </summary>
            public static string Hospital_Disposition = "455401000124109";
            /// <summary> Removal_From_State </summary>
            public static string Removal_From_State = "449941000124103";
            /// <summary> Other </summary>
            public static string Other = "OTH";
            /// <summary> Unknown </summary>
            public static string Unknown = "UNK";
        };

        /// <summary> HistologicalPlacentalExamination </summary>
        public static class HistologicalPlacentalExamination {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "398166005", "Performed", VR.CodeSystems.SCT },
                { "262008008", "Not Performed", VR.CodeSystems.SCT },
                { "397943006", "Planned", VR.CodeSystems.SCT },
            };

            /// <summary> Performed </summary>
            public static string Performed = "398166005";
            /// <summary> Not_Performed </summary>
            public static string Not_Performed = "262008008";
            /// <summary> Planned </summary>
            public static string Planned = "397943006";
        };

        /// <summary> InfectionsDuringPregnancyLiveBirth </summary>
        public static class InfectionsDuringPregnancyLiveBirth {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "15628003", "Gonorrhea (disorder)", VR.CodeSystems.SCT },
                { "76272004", "Syphilis (disorder)", VR.CodeSystems.SCT },
                { "105629000", "Chlamydia (disorder)", VR.CodeSystems.SCT },
                { "66071002", "Hepatitis B (disorder)", VR.CodeSystems.SCT },
                { "50711007", "Hepatitis C (disorder)", VR.CodeSystems.SCT },
                { "33839006", "Genital herpes simplex (disorder)", VR.CodeSystems.SCT },
                { "OTH", "Other", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Gonorrhea_Disorder </summary>
            public static string Gonorrhea_Disorder = "15628003";
            /// <summary> Syphilis_Disorder </summary>
            public static string Syphilis_Disorder = "76272004";
            /// <summary> Chlamydia_Disorder </summary>
            public static string Chlamydia_Disorder = "105629000";
            /// <summary> Hepatitis_B_Disorder </summary>
            public static string Hepatitis_B_Disorder = "66071002";
            /// <summary> Hepatitis_C_Disorder </summary>
            public static string Hepatitis_C_Disorder = "50711007";
            /// <summary> Genital_Herpes_Simplex_Disorder </summary>
            public static string Genital_Herpes_Simplex_Disorder = "33839006";
            /// <summary> Other </summary>
            public static string Other = "OTH";
        };

        /// <summary> InformantRelationshipToMother </summary>
        public static class InformantRelationshipToMother {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "rel_fatherofbaby", "Father of baby", VR.CodeSystems.LocalBFDRCodes },
                { "rel_hospitalemployee", "Hospital employee", VR.CodeSystems.LocalBFDRCodes },
                { "rel_other", "Other (with write in text)", VR.CodeSystems.LocalBFDRCodes },
                { "rel_otherrelative", "Other relative", VR.CodeSystems.LocalBFDRCodes },
            };

            /// <summary> Father_Of_Baby </summary>
            public static string Father_Of_Baby = "rel_fatherofbaby";
            /// <summary> Hospital_Employee </summary>
            public static string Hospital_Employee = "rel_hospitalemployee";
            /// <summary> Other_With_Write_In_Text </summary>
            public static string Other_With_Write_In_Text = "rel_other";
            /// <summary> Other_Relative </summary>
            public static string Other_Relative = "rel_otherrelative";
        };

        /// <summary> LocationTypes </summary>
        public static class LocationTypes {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "loc_birth", "Birth Location", VR.CodeSystems.LocalBFDRCodes },
                { "loc_transfer-from", "Transfer-from Location", VR.CodeSystems.LocalBFDRCodes },
                { "loc_transfer-to", "Transfer-to Location", VR.CodeSystems.LocalBFDRCodes },
            };

            /// <summary> Birth_Location </summary>
            public static string Birth_Location = "loc_birth";
            /// <summary> Transfer_From_Location </summary>
            public static string Transfer_From_Location = "loc_transfer-from";
            /// <summary> Transfer_To_Location </summary>
            public static string Transfer_To_Location = "loc_transfer-to";
        };

        /// <summary> NewbornCongenitalAnomalies </summary>
        public static class NewbornCongenitalAnomalies {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "89369001", "Anencephalus", VR.CodeSystems.SCT },
                { "67531005", "Meningomyelocele/Spina bifida", VR.CodeSystems.SCT },
                { "12770006", "Cyanotic congenital heart disease", VR.CodeSystems.SCT },
                { "17190001", "Congenital diaphragmatic hernia", VR.CodeSystems.SCT },
                { "18735004", "Congenital omphalocele", VR.CodeSystems.SCT },
                { "72951007", "Gastroschisis", VR.CodeSystems.SCT },
                { "67341007", "Longitudinal deficiency of limb - Limb reduction defect (excluding congenital amputation and dwarfing syndromes)", VR.CodeSystems.SCT },
                { "80281008", "Cleft Lip with or without Cleft Palate", VR.CodeSystems.SCT },
                { "87979003", "Cleft palate", VR.CodeSystems.SCT },
                { "70156005", "Anomaly of chromosome pair 21", VR.CodeSystems.SCT },
                { "409709004", "Chromosomal disorder", VR.CodeSystems.SCT },
                { "416010008", "Hypospadias", VR.CodeSystems.SCT },
                { "OTH", "Other", VR.CodeSystems.NullFlavor_HL7_V3 },
            };

            /// <summary> Anencephalus </summary>
            public static string Anencephalus = "89369001";
            /// <summary> Meningomyelocele_Spina_Bifida </summary>
            public static string Meningomyelocele_Spina_Bifida = "67531005";
            /// <summary> Cyanotic_Congenital_Heart_Disease </summary>
            public static string Cyanotic_Congenital_Heart_Disease = "12770006";
            /// <summary> Congenital_Diaphragmatic_Hernia </summary>
            public static string Congenital_Diaphragmatic_Hernia = "17190001";
            /// <summary> Congenital_Omphalocele </summary>
            public static string Congenital_Omphalocele = "18735004";
            /// <summary> Gastroschisis </summary>
            public static string Gastroschisis = "72951007";
            /// <summary> Longitudinal_Deficiency_Of_Limb_Limb_Reduction_Defect_Excluding_Congenital_Amputation_And_Dwarfing_Syndromes </summary>
            public static string Longitudinal_Deficiency_Of_Limb_Limb_Reduction_Defect_Excluding_Congenital_Amputation_And_Dwarfing_Syndromes = "67341007";
            /// <summary> Cleft_Lip_With_Or_Without_Cleft_Palate </summary>
            public static string Cleft_Lip_With_Or_Without_Cleft_Palate = "80281008";
            /// <summary> Cleft_Palate </summary>
            public static string Cleft_Palate = "87979003";
            /// <summary> Anomaly_Of_Chromosome_Pair_21 </summary>
            public static string Anomaly_Of_Chromosome_Pair_21 = "70156005";
            /// <summary> Chromosomal_Disorder </summary>
            public static string Chromosomal_Disorder = "409709004";
            /// <summary> Hypospadias </summary>
            public static string Hypospadias = "416010008";
            /// <summary> Other </summary>
            public static string Other = "OTH";
        };

        /// <summary> NumberPreviousCesareansEditFlags </summary>
        public static class NumberPreviousCesareansEditFlags {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "0", "Edit Passed", VR.CodeSystems.VRCLEditFlags },
                { "1failedVerified", "Edit Failed, Verified", VR.CodeSystems.BFDREditFlags },
            };

            /// <summary> Edit_Passed </summary>
            public static string Edit_Passed = "0";
            /// <summary> Edit_Failed_Verified </summary>
            public static string Edit_Failed_Verified = "1failedVerified";
        };

        /// <summary> ObstetricProcedureOutcome </summary>
        public static class ObstetricProcedureOutcome {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "385669000", "Successful (qualifier value)", VR.CodeSystems.SCT },
                { "385671000", "Unsuccessful (qualifier value)", VR.CodeSystems.SCT },
            };

            /// <summary> Successful_Qualifier_Value </summary>
            public static string Successful_Qualifier_Value = "385669000";
            /// <summary> Unsuccessful_Qualifier_Value </summary>
            public static string Unsuccessful_Qualifier_Value = "385671000";
        };

        /// <summary> PregnancyReportEditFlags </summary>
        public static class PregnancyReportEditFlags {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "0", "Edit Passed", VR.CodeSystems.VRCLEditFlags },
                { "1", "Edit Failed, Data Queried, and Verified", VR.CodeSystems.VRCLEditFlags },
                { "2", "Edit Failed, Data Queried, but not Verified", VR.CodeSystems.VRCLEditFlags },
            };

            /// <summary> Edit_Passed </summary>
            public static string Edit_Passed = "0";
            /// <summary> Edit_Failed_Data_Queried_And_Verified </summary>
            public static string Edit_Failed_Data_Queried_And_Verified = "1";
            /// <summary> Edit_Failed_Data_Queried_But_Not_Verified </summary>
            public static string Edit_Failed_Data_Queried_But_Not_Verified = "2";
        };

        /// <summary> UnitsOfGestationalAge </summary>
        public static class UnitsOfGestationalAge {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "d", "Days", VR.CodeSystems.UnitsOfMeasure },
                { "wk", "Weeks", VR.CodeSystems.UnitsOfMeasure },
            };

            /// <summary> Days </summary>
            public static string Days = "d";
            /// <summary> Weeks </summary>
            public static string Weeks = "wk";
        };

        /// <summary> CigaretteSmokingBeforeDuringPregnancy </summary>
        public static class CigaretteSmokingBeforeDuringPregnancy {
            /// <summary> Codes </summary>
            public static string[,] Codes = {
                { "64794-1", "In the 3 months before you got pregnant, how many cigarettes did you smoke on an average day [PhenX]", VR.CodeSystems.LOINC },
                { "87298-6", "Cigarettes smoked per day by Mother--1st trimester", VR.CodeSystems.LOINC },
                { "87299-4", "Cigarettes smoked per day by Mother--2nd trimester", VR.CodeSystems.LOINC },
                { "64795-8", "In the last 3 months of your pregnancy, how many cigarettes did you smoke on an average day [PhenX]", VR.CodeSystems.LOINC },
            };

            /// <summary> In_The_3_Months_Before_You_Got_Pregnant_How_Many_Cigarettes_Did_You_Smoke_On_An_Average_Day_Phenx </summary>
            public static string In_The_3_Months_Before_You_Got_Pregnant_How_Many_Cigarettes_Did_You_Smoke_On_An_Average_Day_Phenx = "64794-1";
            /// <summary> Cigarettes_Smoked_Per_Day_By_Mother_1st_Trimester </summary>
            public static string Cigarettes_Smoked_Per_Day_By_Mother_1st_Trimester = "87298-6";
            /// <summary> Cigarettes_Smoked_Per_Day_By_Mother_2nd_Trimester </summary>
            public static string Cigarettes_Smoked_Per_Day_By_Mother_2nd_Trimester = "87299-4";
            /// <summary> In_The_Last_3_Months_Of_Your_Pregnancy_How_Many_Cigarettes_Did_You_Smoke_On_An_Average_Day_Phenx </summary>
            public static string In_The_Last_3_Months_Of_Your_Pregnancy_How_Many_Cigarettes_Did_You_Smoke_On_An_Average_Day_Phenx = "64795-8";
        };

    }
}
