// TODO: this file should be generated by a script similar to the VRDR URLs.cs file using the common VR IG
// and should provide the parent classes to the classes in the VRDR and BFDR URLs.cs files
// Until the IG is created, this file is produced manually and there is no inheritance

namespace VR
{
    // <summary>Profile URLs</summary>
    // public static class ProfileURL
    // {}

    /// <summary>Extension URLs</summary>
    public static class ExtensionURL
    {
        /// <summary>URL for PartialDateTime</summary>
        public const string PartialDateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDateTime";

        /// <summary>URL for PartialDate</summary>
        public const string PartialDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDate";


        /// <summary>URL for DateDay</summary>
        public const string DateDay = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Day";

        /// <summary>URL for DateYear</summary>
        public const string DateYear = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Year";


        /// <summary>URL for DateMonth</summary>
        public const string DateMonth = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Month";

        /// <summary>URL for DateTime</summary>
        public const string DateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Time";

        /// <summary>URL for CityCode</summary>
        public const string CityCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/CityCode";

        /// <summary>URL for DistrictCode</summary>
        public const string DistrictCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/DistrictCode";

        /// <summary>URL for LocationJurisdictionId</summary>
        public const string LocationJurisdictionId = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Location-Jurisdiction-Id";

        /// <summary>URL for PreDirectional</summary>
        public const string PreDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PreDirectional";

        /// <summary>URL for StreetName</summary>
        public const string StreetName = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetName";

        /// <summary>URL for StreetNumber</summary>
        public const string StreetNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetNumber";

        /// <summary>URL for StreetDesignator</summary>
        public const string StreetDesignator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetDesignator";

        /// <summary>URL for PostDirectional</summary>
        public const string PostDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PostDirectional";

        /// <summary>URL for UnitOrAptNumber</summary>
        public const string UnitOrAptNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/UnitOrAptNumber";

        /// <summary>URL for CertificateNumber</summary>
        public const string CertificateNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/CertificateNumber";

    }

    // <summary>IG URLs</summary>
    // public static class IGURL
    // {
    // }
}
