// DO NOT EDIT MANUALLY! This file was generated by the script "scripts/generate_url_strings_from_VR_IG.rb"

namespace VR
{
    /// <summary>Profile URLs</summary>
    public static class ProfileURL
    {
        /// <summary>URL for AuxiliaryStateIdentifier1VitalRecords</summary>
        public const string AuxiliaryStateIdentifier1VitalRecords = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/AuxiliaryStateIdentifier1";

        /// <summary>URL for AuxiliaryStateIdentifier2VitalRecords</summary>
        public const string AuxiliaryStateIdentifier2VitalRecords = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/AuxiliaryStateIdentifier2";

        /// <summary>URL for CertificateNumber</summary>
        public const string CertificateNumber = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/CertificateNumber";

        /// <summary>URL for Location</summary>
        public const string Location = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Location-vr";

        /// <summary>URL for EducationLevel</summary>
        public const string EducationLevel = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Observation-education-level-vr";

        /// <summary>URL for EmergingIssues</summary>
        public const string EmergingIssues = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Observation-emerging-issues-vr";

        /// <summary>URL for Child</summary>
        public const string Child = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Patient-child-vr";

        /// <summary>URL for Mother</summary>
        public const string Mother = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Patient-mother-vr";

        /// <summary>URL for Patient</summary>
        public const string Patient = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Patient-vr";

        /// <summary>URL for Practitioner</summary>
        public const string Practitioner = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Practitioner-vr";

        /// <summary>URL for RelatedPersonFatherNatural</summary>
        public const string RelatedPersonFatherNatural = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/RelatedPerson-father-natural-vr";

        /// <summary>URL for RelatedPersonFather</summary>
        public const string RelatedPersonFather = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/RelatedPerson-father-vr";

        /// <summary>URL for RelatedPersonMother</summary>
        public const string RelatedPersonMother = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/RelatedPerson-mother-vr";

        /// <summary>URL for RelatedPersonParent</summary>
        public const string RelatedPersonParent = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/RelatedPerson-parent-vr";

        /// <summary>URL for CodedRaceAndEthnicity</summary>
        public const string CodedRaceAndEthnicity = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/coded-race-and-ethnicity-vr";

        /// <summary>URL for InputRaceAndEthnicity</summary>
        public const string InputRaceAndEthnicity = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/input-race-and-ethnicity-vr";

    }

    /// <summary>Extension URLs</summary>
    public class ExtensionURL
    {

        /// <summary>URL for BypassEditFlag</summary>
        public const string BypassEditFlag = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/BypassEditFlag";

        /// <summary>URL for CityCode</summary>
        public const string CityCode = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/CityCode";

        /// <summary>URL for DistrictCode</summary>
        public const string DistrictCode = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/DistrictCode";

        /// <summary>URL for LocationJurisdictionId</summary>
        public const string LocationJurisdictionId = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-jurisdiction-id-vr";

        /// <summary>URL for PartialDateTime</summary>
        public const string PartialDateTime = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-partial-date-time-vr";

        /// <summary>URL for PartialDate</summary>
        public const string PartialDate = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-partial-date-vr";

        /// <summary>URL for PatientFetalDeath</summary>
        public const string PatientFetalDeath = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-patient-fetal-death-vr";

        /// <summary>URL for RelatedpersonBirthplace</summary>
        public const string RelatedpersonBirthplace = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-relatedperson-birthplace-vr";

        /// <summary>URL for ReportedParentAgeAtDelivery</summary>
        public const string ReportedParentAgeAtDelivery = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-reported-parent-age-at-delivery-vr";

        /// <summary>URL for WithinCityLimitsIndicator</summary>
        public const string WithinCityLimitsIndicator = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-within-city-limits-indicator-vr";

        /// <summary>URL for PostDirectional</summary>
        public const string PostDirectional = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/PostDirectional";

        /// <summary>URL for PreDirectional</summary>
        public const string PreDirectional = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/PreDirectional";

        /// <summary>URL for StreetDesignator</summary>
        public const string StreetDesignator = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/StreetDesignator";

        /// <summary>URL for StreetName</summary>
        public const string StreetName = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/StreetName";

        /// <summary>URL for StreetNumber</summary>
        public const string StreetNumber = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/StreetNumber";

        /// <summary>URL for UnitOrAptNumber</summary>
        public const string UnitOrAptNumber = "http://hl7.org/fhir/us/vr-common-library/StructureDefinition/UnitOrAptNumber";


        /// <summary>URL for PatientBirthTime as defined in the VitalRecords IG</summary>
        public const string PatientBirthTime = "http://hl7.org/fhir/StructureDefinition/patient-birthTime";  

        /// <summary>URL for PartialDate Day as defined in the VitalRecords IG</summary>
        public const string PartialDateDayVR = "day";     

        /// <summary>URL for PartialDate Month as defined in the VitalRecords IG</summary>
        public const string PartialDateMonthVR = "month";

        /// <summary>URL for PartialDateTime Year as defined in the VitalRecords IG</summary>
        public const string PartialDateYearVR = "year";

        /// <summary>URL for PartialDateTime Time as defined in the VitalRecords IG</summary>
        public const string PartialDateTimeVR = "time";

    }

    /// <summary>IG URLs</summary>
    public static class IGURL
    {
        /// <summary>URL for AuxiliaryStateIdentifier1VitalRecords</summary>
        public const string AuxiliaryStateIdentifier1VitalRecords = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-AuxiliaryStateIdentifier1.html";

        /// <summary>URL for AuxiliaryStateIdentifier2VitalRecords</summary>
        public const string AuxiliaryStateIdentifier2VitalRecords = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-AuxiliaryStateIdentifier2.html";

        /// <summary>URL for BypassEditFlag</summary>
        public const string BypassEditFlag = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-BypassEditFlag.html";

        /// <summary>URL for CertificateNumber</summary>
        public const string CertificateNumber = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-CertificateNumber.html";

        /// <summary>URL for CityCode</summary>
        public const string CityCode = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-CityCode.html";

        /// <summary>URL for DistrictCode</summary>
        public const string DistrictCode = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-DistrictCode.html";

        /// <summary>URL for LocationJurisdictionId</summary>
        public const string LocationJurisdictionId = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Extension-jurisdiction-id-vr.html";

        /// <summary>URL for PartialDateTime</summary>
        public const string PartialDateTime = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Extension-partial-date-time-vr.html";

        /// <summary>URL for PartialDate</summary>
        public const string PartialDate = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Extension-partial-date-vr.html";

        /// <summary>URL for PatientFetalDeath</summary>
        public const string PatientFetalDeath = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Extension-patient-fetal-death-vr.html";

        /// <summary>URL for RelatedpersonBirthplace</summary>
        public const string RelatedpersonBirthplace = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Extension-relatedperson-birthplace-vr.html";

        /// <summary>URL for ReportedParentAgeAtDelivery</summary>
        public const string ReportedParentAgeAtDelivery = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Extension-reported-parent-age-at-delivery-vr.html";

        /// <summary>URL for WithinCityLimitsIndicator</summary>
        public const string WithinCityLimitsIndicator = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Extension-within-city-limits-indicator-vr.html";

        /// <summary>URL for Location</summary>
        public const string Location = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Location-vr.html";

        /// <summary>URL for EducationLevel</summary>
        public const string EducationLevel = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Observation-education-level-vr.html";

        /// <summary>URL for EmergingIssues</summary>
        public const string EmergingIssues = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Observation-emerging-issues-vr.html";

        /// <summary>URL for Child</summary>
        public const string Child = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Patient-child-vr.html";

        /// <summary>URL for Mother</summary>
        public const string Mother = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Patient-mother-vr.html";

        /// <summary>URL for Patient</summary>
        public const string Patient = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Patient-vr.html";

        /// <summary>URL for PostDirectional</summary>
        public const string PostDirectional = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-PostDirectional.html";

        /// <summary>URL for Practitioner</summary>
        public const string Practitioner = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-Practitioner-vr.html";

        /// <summary>URL for PreDirectional</summary>
        public const string PreDirectional = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-PreDirectional.html";

        /// <summary>URL for RelatedPersonFatherNatural</summary>
        public const string RelatedPersonFatherNatural = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-RelatedPerson-father-natural-vr.html";

        /// <summary>URL for RelatedPersonFather</summary>
        public const string RelatedPersonFather = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-RelatedPerson-father-vr.html";

        /// <summary>URL for RelatedPersonMother</summary>
        public const string RelatedPersonMother = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-RelatedPerson-mother-vr.html";

        /// <summary>URL for RelatedPersonParent</summary>
        public const string RelatedPersonParent = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-RelatedPerson-parent-vr.html";

        /// <summary>URL for StreetDesignator</summary>
        public const string StreetDesignator = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-StreetDesignator.html";

        /// <summary>URL for StreetName</summary>
        public const string StreetName = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-StreetName.html";

        /// <summary>URL for StreetNumber</summary>
        public const string StreetNumber = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-StreetNumber.html";

        /// <summary>URL for UnitOrAptNumber</summary>
        public const string UnitOrAptNumber = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-UnitOrAptNumber.html";

        /// <summary>URL for CodedRaceAndEthnicity</summary>
        public const string CodedRaceAndEthnicity = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-coded-race-and-ethnicity-vr.html";

        /// <summary>URL for InputRaceAndEthnicity</summary>
        public const string InputRaceAndEthnicity = "https://hl7.org/fhir/us/vr-common-library/StructureDefinition-input-race-and-ethnicity-vr.html";

    }
}
