// DO NOT EDIT MANUALLY! This file was generated by the script "scripts/generate_concept_mappings.rb"

using System;
using System.Collections.Generic;

namespace VRDR
{
    /// <summary>Mappings between IJE and FHIR value sets</summary>
    public static class Mappings
    {
        /// <summary>Mappings for ActivityAtTimeOfDeath</summary>
        public static class ActivityAtTimeOfDeath
        {
            /// <summary>IJE -> FHIR Mapping for ActivityAtTimeOfDeath</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
                { "8", "8" },
                { "9", "9" },
            };
            /// <summary>FHIR -> IJE Mapping for ActivityAtTimeOfDeath</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
                { "8", "8" },
                { "9", "9" },
            };
        }
        /// <summary>Mappings for AdministrativeGender</summary>
        public static class AdministrativeGender
        {
            /// <summary>IJE -> FHIR Mapping for AdministrativeGender</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "M", "male" },
                { "F", "female" },
                { "U", "unknown" },
            };
            /// <summary>FHIR -> IJE Mapping for AdministrativeGender</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "male", "M" },
                { "female", "F" },
                { "unknown", "U" },
            };
        }
        /// <summary>Mappings for CertifierTypes</summary>
        public static class CertifierTypes
        {
            /// <summary>IJE -> FHIR Mapping for CertifierTypes</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "D", "434651000124107" },
                { "P", "434641000124105" },
                { "M", "455381000124109" },
            };
            /// <summary>FHIR -> IJE Mapping for CertifierTypes</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "434651000124107", "D" },
                { "434641000124105", "P" },
                { "455381000124109", "M" },
            };
        }
        /// <summary>Mappings for ContributoryTobaccoUse</summary>
        public static class ContributoryTobaccoUse
        {
            /// <summary>IJE -> FHIR Mapping for ContributoryTobaccoUse</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "Y", "373066001" },
                { "N", "373067005" },
                { "P", "2931005" },
                { "U", "UNK" },
                { "C", "NI" },
            };
            /// <summary>FHIR -> IJE Mapping for ContributoryTobaccoUse</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "373066001", "Y" },
                { "373067005", "N" },
                { "2931005", "P" },
                { "UNK", "U" },
                { "NI", "C" },
            };
        }
        /// <summary>Mappings for DeathPregnancyStatus</summary>
        public static class DeathPregnancyStatus
        {
            /// <summary>IJE -> FHIR Mapping for DeathPregnancyStatus</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
                { "7", "7" },
                { "9", "9" },
                { "8", "NA" },
            };
            /// <summary>FHIR -> IJE Mapping for DeathPregnancyStatus</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
                { "7", "7" },
                { "9", "9" },
                { "NA", "8" },
            };
        }
        /// <summary>Mappings for EditBypass0124</summary>
        public static class EditBypass0124
        {
            /// <summary>IJE -> FHIR Mapping for EditBypass0124</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
                { "4", "4" },
            };
            /// <summary>FHIR -> IJE Mapping for EditBypass0124</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
                { "4", "4" },
            };
        }
        /// <summary>Mappings for EditBypass012</summary>
        public static class EditBypass012
        {
            /// <summary>IJE -> FHIR Mapping for EditBypass012</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
            };
            /// <summary>FHIR -> IJE Mapping for EditBypass012</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
            };
        }
        /// <summary>Mappings for EditBypass01</summary>
        public static class EditBypass01
        {
            /// <summary>IJE -> FHIR Mapping for EditBypass01</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
            };
            /// <summary>FHIR -> IJE Mapping for EditBypass01</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
            };
        }
        /// <summary>Mappings for FilingFormat</summary>
        public static class FilingFormat
        {
            /// <summary>IJE -> FHIR Mapping for FilingFormat</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "electronic" },
                { "1", "paper" },
                { "2", "mixed" },
            };
            /// <summary>FHIR -> IJE Mapping for FilingFormat</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "electronic", "0" },
                { "paper", "1" },
                { "mixed", "2" },
            };
        }
        /// <summary>Mappings for IntentionalReject</summary>
        public static class IntentionalReject
        {
            /// <summary>IJE -> FHIR Mapping for IntentionalReject</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
                { "5", "5" },
                { "9", "9" },
            };
            /// <summary>FHIR -> IJE Mapping for IntentionalReject</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
                { "5", "5" },
                { "9", "9" },
            };
        }
        /// <summary>Mappings for MannerOfDeath</summary>
        public static class MannerOfDeath
        {
            /// <summary>IJE -> FHIR Mapping for MannerOfDeath</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "N", "38605008" },
                { "A", "7878000" },
                { "S", "44301001" },
                { "H", "27935005" },
                { "P", "185973002" },
                { "C", "65037004" },
            };
            /// <summary>FHIR -> IJE Mapping for MannerOfDeath</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "38605008", "N" },
                { "7878000", "A" },
                { "44301001", "S" },
                { "27935005", "H" },
                { "185973002", "P" },
                { "65037004", "C" },
            };
        }
        /// <summary>Mappings for MethodOfDisposition</summary>
        public static class MethodOfDisposition
        {
            /// <summary>IJE -> FHIR Mapping for MethodOfDisposition</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "B", "449971000124106" },
                { "C", "449961000124104" },
                { "D", "449951000124101" },
                { "E", "449931000124108" },
                { "R", "449941000124103" },
                { "O", "OTH" },
                { "U", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for MethodOfDisposition</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "449971000124106", "B" },
                { "449961000124104", "C" },
                { "449951000124101", "D" },
                { "449931000124108", "E" },
                { "449941000124103", "R" },
                { "OTH", "O" },
                { "UNK", "U" },
            };
        }
        /// <summary>Mappings for PlaceOfDeath</summary>
        public static class PlaceOfDeath
        {
            /// <summary>IJE -> FHIR Mapping for PlaceOfDeath</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "16983000" },
                { "2", "450391000124102" },
                { "3", "63238001" },
                { "4", "440081000124100" },
                { "5", "440071000124103" },
                { "6", "450381000124100" },
                { "7", "OTH" },
                { "9", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for PlaceOfDeath</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "16983000", "1" },
                { "450391000124102", "2" },
                { "63238001", "3" },
                { "440081000124100", "4" },
                { "440071000124103", "5" },
                { "450381000124100", "6" },
                { "OTH", "7" },
                { "UNK", "9" },
            };
        }
        /// <summary>Mappings for PlaceOfInjury</summary>
        public static class PlaceOfInjury
        {
            /// <summary>IJE -> FHIR Mapping for PlaceOfInjury</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "LA14084-0" },
                { "1", "LA14085-7" },
                { "2", "LA14086-5" },
                { "3", "LA14088-1" },
                { "4", "LA14089-9" },
                { "5", "LA14090-7" },
                { "6", "LA14091-5" },
                { "7", "LA14092-3" },
                { "9", "LA14093-1" },
                { "8", "OTH" },
            };
            /// <summary>FHIR -> IJE Mapping for PlaceOfInjury</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "LA14084-0", "0" },
                { "LA14085-7", "1" },
                { "LA14086-5", "2" },
                { "LA14088-1", "3" },
                { "LA14089-9", "4" },
                { "LA14090-7", "5" },
                { "LA14091-5", "6" },
                { "LA14092-3", "7" },
                { "LA14093-1", "9" },
                { "OTH", "8" },
            };
        }
        /// <summary>Mappings for ReplaceStatus</summary>
        public static class ReplaceStatus
        {
            /// <summary>IJE -> FHIR Mapping for ReplaceStatus</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "original" },
                { "1", "updated" },
                { "2", "updated_notforNCHS" },
            };
            /// <summary>FHIR -> IJE Mapping for ReplaceStatus</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "original", "0" },
                { "updated", "1" },
                { "updated_notforNCHS", "2" },
            };
        }
        /// <summary>Mappings for SpouseAlive</summary>
        public static class SpouseAlive
        {
            /// <summary>IJE -> FHIR Mapping for SpouseAlive</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "1", "Y" },
                { "2", "N" },
                { "8", "NA" },
                { "9", "UNK" },
            };
            /// <summary>FHIR -> IJE Mapping for SpouseAlive</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "Y", "1" },
                { "N", "2" },
                { "NA", "8" },
                { "UNK", "9" },
            };
        }
        /// <summary>Mappings for SystemReject</summary>
        public static class SystemReject
        {
            /// <summary>IJE -> FHIR Mapping for SystemReject</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
            };
            /// <summary>FHIR -> IJE Mapping for SystemReject</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "0", "0" },
                { "1", "1" },
                { "2", "2" },
                { "3", "3" },
                { "4", "4" },
            };
        }
        /// <summary>Mappings for TransaxConversion</summary>
        public static class TransaxConversion
        {
            /// <summary>IJE -> FHIR Mapping for TransaxConversion</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "3", "3" },
                { "4", "4" },
                { "5", "5" },
                { "6", "6" },
            };
            /// <summary>FHIR -> IJE Mapping for TransaxConversion</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "3", "3" },
                { "4", "4" },
                { "5", "5" },
                { "6", "6" },
            };
        }
        /// <summary>Mappings for TransportationIncidentRole</summary>
        public static class TransportationIncidentRole
        {
            /// <summary>IJE -> FHIR Mapping for TransportationIncidentRole</summary>
            public readonly static Dictionary<string, string> IJEToFHIR = new Dictionary<string, string>
            {
                { "DR", "236320001" },
                { "PA", "257500003" },
                { "PE", "257518000" },
            };
            /// <summary>FHIR -> IJE Mapping for TransportationIncidentRole</summary>
            public readonly static Dictionary<string, string> FHIRToIJE = new Dictionary<string, string>
            {
                { "236320001", "DR" },
                { "257500003", "PA" },
                { "257518000", "PE" },
            };
        }
    }
}
