// DO NOT EDIT MANUALLY! This file was generated by the script "scripts/generate_url_strings_from_VRDR_IG.rb"

namespace VRDR
{
    /// <summary>Profile URLs</summary>
    public static class ProfileURL
    {
        /// <summary>URL for ActivityAtTimeOfDeath</summary>
        public const string ActivityAtTimeOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-activity-at-time-of-death";

        /// <summary>URL for AutomatedUnderlyingCauseOfDeath</summary>
        public const string AutomatedUnderlyingCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-automated-underlying-cause-of-death";

        /// <summary>URL for AutopsyPerformedIndicator</summary>
        public const string AutopsyPerformedIndicator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-autopsy-performed-indicator";

        /// <summary>URL for BirthRecordIdentifierChild</summary>
        public const string BirthRecordIdentifierChild = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-birth-record-identifier-child";

        /// <summary>URL for BirthRecordIdentifier</summary>
        public const string BirthRecordIdentifier = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-birth-record-identifier";

        /// <summary>URL for CauseOfDeathCodedContentBundle</summary>
        public const string CauseOfDeathCodedContentBundle = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-coded-content-bundle";

        /// <summary>URL for CauseOfDeathPart1</summary>
        public const string CauseOfDeathPart1 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part1";

        /// <summary>URL for CauseOfDeathPart2</summary>
        public const string CauseOfDeathPart2 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part2";

        /// <summary>URL for Certifier</summary>
        public const string Certifier = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-certifier";

        /// <summary>URL for CodingStatusValues</summary>
        public const string CodingStatusValues = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coding-status-values";

        /// <summary>URL for DeathCertificateDocument</summary>
        public const string DeathCertificateDocument = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate-document";

        /// <summary>URL for DeathCertificate</summary>
        public const string DeathCertificate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate";

        /// <summary>URL for DeathCertification</summary>
        public const string DeathCertification = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certification";

        /// <summary>URL for DeathDate</summary>
        public const string DeathDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-date";

        /// <summary>URL for DeathLocation</summary>
        public const string DeathLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-location";

        /// <summary>URL for DecedentAge</summary>
        public const string DecedentAge = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-age";

        /// <summary>URL for DecedentDispositionMethod</summary>
        public const string DecedentDispositionMethod = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-disposition-method";

        /// <summary>URL for DecedentEducationLevel</summary>
        public const string DecedentEducationLevel = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-education-level";

        /// <summary>URL for DecedentFather</summary>
        public const string DecedentFather = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-father";

        /// <summary>URL for DecedentMilitaryService</summary>
        public const string DecedentMilitaryService = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-military-service";

        /// <summary>URL for DecedentMother</summary>
        public const string DecedentMother = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-mother";

        /// <summary>URL for DecedentPregnancyStatus</summary>
        public const string DecedentPregnancyStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-pregnancy-status";

        /// <summary>URL for DecedentSpouse</summary>
        public const string DecedentSpouse = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-spouse";

        /// <summary>URL for DecedentUsualWork</summary>
        public const string DecedentUsualWork = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-usual-work";

        /// <summary>URL for Decedent</summary>
        public const string Decedent = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent";

        /// <summary>URL for DemographicCodedContentBundle</summary>
        public const string DemographicCodedContentBundle = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-demographic-coded-content-bundle";

        /// <summary>URL for DispositionLocation</summary>
        public const string DispositionLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-disposition-location";

        /// <summary>URL for EntityAxisCauseOfDeath</summary>
        public const string EntityAxisCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-entity-axis-cause-of-death";

        /// <summary>URL for ExaminerContacted</summary>
        public const string ExaminerContacted = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-examiner-contacted";

        /// <summary>URL for FetalDeathRecordIdentifier</summary>
        public const string FetalDeathRecordIdentifier = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-fetal-death-record-identifier";

        /// <summary>URL for FuneralHome</summary>
        public const string FuneralHome = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-funeral-home";

        /// <summary>URL for InjuryIncident</summary>
        public const string InjuryIncident = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-incident";

        /// <summary>URL for InjuryLocation</summary>
        public const string InjuryLocation = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-location";

        /// <summary>URL for MannerOfDeath</summary>
        public const string MannerOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manner-of-death";

        /// <summary>URL for ManualUnderlyingCauseOfDeath</summary>
        public const string ManualUnderlyingCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manual-underlying-cause-of-death";

        /// <summary>URL for MortalityRosterBundle</summary>
        public const string MortalityRosterBundle = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-mortality-roster-bundle";

        /// <summary>URL for Mortician</summary>
        public const string Mortician = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-mortician";

        /// <summary>URL for PlaceOfInjury</summary>
        public const string PlaceOfInjury = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-place-of-injury";

        /// <summary>URL for RecordAxisCauseOfDeath</summary>
        public const string RecordAxisCauseOfDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-record-axis-cause-of-death";

        /// <summary>URL for SurgeryDate</summary>
        public const string SurgeryDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-surgery-date";

        /// <summary>URL for TobaccoUseContributedToDeath</summary>
        public const string TobaccoUseContributedToDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-tobacco-use-contributed-to-death";

    }

    /// <summary>Extension URLs</summary>
    public static class ExtensionURL
    {
        /// <summary>URL for AliasStatus</summary>
        public const string AliasStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AliasStatus";

        /// <summary>URL for FilingFormat</summary>
        public const string FilingFormat = "http://hl7.org/fhir/us/vrdr/StructureDefinition/FilingFormat";

        /// <summary>URL for NVSSSexAtDeath</summary>
        public const string NVSSSexAtDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/NVSS-SexAtDeath";

        /// <summary>URL for ReplaceStatus</summary>
        public const string ReplaceStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/ReplaceStatus";

        /// <summary>URL for SpouseAlive</summary>
        public const string SpouseAlive = "http://hl7.org/fhir/us/vrdr/StructureDefinition/SpouseAlive";

        /// <summary>URL for StateSpecificField</summary>
        public const string StateSpecificField = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StateSpecificField";

        /// <summary>URL for IndustryOccupationCodedContentBundle</summary>
        public const string IndustryOccupationCodedContentBundle = "http://hl7.org/fhir/us/vrdr/StructureDefinition/industry-occupation-coded-content-bundle";

        /// <summary>URL for PractitionerRole</summary>
        public const string PractitionerRole = "http://hl7.org/fhir/us/vrdr/StructureDefinition/practitioner-role";

    }
     /// <summary>CodeSystem URLs</summary>
     public class CodeSystemURL
    {

        /// <summary>URL for DeathPregnancyStatusCS</summary>
        public const string DeathPregnancyStatusCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/CodeSystem-death-pregnancy-status";

        /// <summary>URL for ActivityAtTimeOfDeathCS</summary>
        public const string ActivityAtTimeOfDeathCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-activity-at-time-of-death-cs";

        /// <summary>URL for ComponentCS</summary>
        public const string ComponentCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-component-cs";

        /// <summary>URL for DateOfDeathDeterminationMethodsCS</summary>
        public const string DateOfDeathDeterminationMethodsCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-date-of-death-determination-methods-cs";

        /// <summary>URL for DocumentSectionCS</summary>
        public const string DocumentSectionCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-document-section-cs";

        /// <summary>URL for FilingFormatCS</summary>
        public const string FilingFormatCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-filing-format-cs";

        /// <summary>URL for IntentionalRejectCS</summary>
        public const string IntentionalRejectCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-intentional-reject-cs";

        /// <summary>URL for LocationTypeCS</summary>
        public const string LocationTypeCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-location-type-cs";

        /// <summary>URL for ObservationsCS</summary>
        public const string ObservationsCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-observations-cs";

        /// <summary>URL for OrganizationTypeCS</summary>
        public const string OrganizationTypeCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-organization-type-cs";

        /// <summary>URL for ReplaceStatusCS</summary>
        public const string ReplaceStatusCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-replace-status-cs";

        /// <summary>URL for SuperMicarPlaceOfInjuryCS</summary>
        public const string SuperMicarPlaceOfInjuryCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-system-placeofinjury-cs";

        /// <summary>URL for SystemRejectCS</summary>
        public const string SystemRejectCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-system-reject-cs";

        /// <summary>URL for TransaxConversionCS</summary>
        public const string TransaxConversionCS = "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-transax-conversion-cs";

    }

    /// <summary>IG URLs</summary>
    public static class IGURL
    {
        /// <summary>URL for AliasStatus</summary>
        public const string AliasStatus = "https://hl7.org/fhir/us/vrdr/StructureDefinition-AliasStatus.html";

        /// <summary>URL for FilingFormat</summary>
        public const string FilingFormat = "https://hl7.org/fhir/us/vrdr/StructureDefinition-FilingFormat.html";

        /// <summary>URL for NVSSSexAtDeath</summary>
        public const string NVSSSexAtDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-NVSS-SexAtDeath.html";

        /// <summary>URL for ReplaceStatus</summary>
        public const string ReplaceStatus = "https://hl7.org/fhir/us/vrdr/StructureDefinition-ReplaceStatus.html";

        /// <summary>URL for SpouseAlive</summary>
        public const string SpouseAlive = "https://hl7.org/fhir/us/vrdr/StructureDefinition-SpouseAlive.html";

        /// <summary>URL for StateSpecificField</summary>
        public const string StateSpecificField = "https://hl7.org/fhir/us/vrdr/StructureDefinition-StateSpecificField.html";

        /// <summary>URL for IndustryOccupationCodedContentBundle</summary>
        public const string IndustryOccupationCodedContentBundle = "https://hl7.org/fhir/us/vrdr/StructureDefinition-industry-occupation-coded-content-bundle.html";

        /// <summary>URL for PractitionerRole</summary>
        public const string PractitionerRole = "https://hl7.org/fhir/us/vrdr/StructureDefinition-practitioner-role.html";

        /// <summary>URL for ActivityAtTimeOfDeath</summary>
        public const string ActivityAtTimeOfDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-activity-at-time-of-death.html";

        /// <summary>URL for AutomatedUnderlyingCauseOfDeath</summary>
        public const string AutomatedUnderlyingCauseOfDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-automated-underlying-cause-of-death.html";

        /// <summary>URL for AutopsyPerformedIndicator</summary>
        public const string AutopsyPerformedIndicator = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-autopsy-performed-indicator.html";

        /// <summary>URL for BirthRecordIdentifierChild</summary>
        public const string BirthRecordIdentifierChild = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-birth-record-identifier-child.html";

        /// <summary>URL for BirthRecordIdentifier</summary>
        public const string BirthRecordIdentifier = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-birth-record-identifier.html";

        /// <summary>URL for CauseOfDeathCodedContentBundle</summary>
        public const string CauseOfDeathCodedContentBundle = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-cause-of-death-coded-content-bundle.html";

        /// <summary>URL for CauseOfDeathPart1</summary>
        public const string CauseOfDeathPart1 = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-cause-of-death-part1.html";

        /// <summary>URL for CauseOfDeathPart2</summary>
        public const string CauseOfDeathPart2 = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-cause-of-death-part2.html";

        /// <summary>URL for Certifier</summary>
        public const string Certifier = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-certifier.html";

        /// <summary>URL for CodingStatusValues</summary>
        public const string CodingStatusValues = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-coding-status-values.html";

        /// <summary>URL for DeathCertificateDocument</summary>
        public const string DeathCertificateDocument = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-death-certificate-document.html";

        /// <summary>URL for DeathCertificate</summary>
        public const string DeathCertificate = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-death-certificate.html";

        /// <summary>URL for DeathCertification</summary>
        public const string DeathCertification = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-death-certification.html";

        /// <summary>URL for DeathDate</summary>
        public const string DeathDate = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-death-date.html";

        /// <summary>URL for DeathLocation</summary>
        public const string DeathLocation = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-death-location.html";

        /// <summary>URL for DecedentAge</summary>
        public const string DecedentAge = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-age.html";

        /// <summary>URL for DecedentDispositionMethod</summary>
        public const string DecedentDispositionMethod = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-disposition-method.html";

        /// <summary>URL for DecedentEducationLevel</summary>
        public const string DecedentEducationLevel = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-education-level.html";

        /// <summary>URL for DecedentFather</summary>
        public const string DecedentFather = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-father.html";

        /// <summary>URL for DecedentMilitaryService</summary>
        public const string DecedentMilitaryService = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-military-service.html";

        /// <summary>URL for DecedentMother</summary>
        public const string DecedentMother = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-mother.html";

        /// <summary>URL for DecedentPregnancyStatus</summary>
        public const string DecedentPregnancyStatus = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-pregnancy-status.html";

        /// <summary>URL for DecedentSpouse</summary>
        public const string DecedentSpouse = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-spouse.html";

        /// <summary>URL for DecedentUsualWork</summary>
        public const string DecedentUsualWork = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent-usual-work.html";

        /// <summary>URL for Decedent</summary>
        public const string Decedent = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-decedent.html";

        /// <summary>URL for DemographicCodedContentBundle</summary>
        public const string DemographicCodedContentBundle = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-demographic-coded-content-bundle.html";

        /// <summary>URL for DispositionLocation</summary>
        public const string DispositionLocation = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-disposition-location.html";

        /// <summary>URL for EntityAxisCauseOfDeath</summary>
        public const string EntityAxisCauseOfDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-entity-axis-cause-of-death.html";

        /// <summary>URL for ExaminerContacted</summary>
        public const string ExaminerContacted = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-examiner-contacted.html";

        /// <summary>URL for FetalDeathRecordIdentifier</summary>
        public const string FetalDeathRecordIdentifier = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-fetal-death-record-identifier.html";

        /// <summary>URL for FuneralHome</summary>
        public const string FuneralHome = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-funeral-home.html";

        /// <summary>URL for InjuryIncident</summary>
        public const string InjuryIncident = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-injury-incident.html";

        /// <summary>URL for InjuryLocation</summary>
        public const string InjuryLocation = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-injury-location.html";

        /// <summary>URL for MannerOfDeath</summary>
        public const string MannerOfDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-manner-of-death.html";

        /// <summary>URL for ManualUnderlyingCauseOfDeath</summary>
        public const string ManualUnderlyingCauseOfDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-manual-underlying-cause-of-death.html";

        /// <summary>URL for MortalityRosterBundle</summary>
        public const string MortalityRosterBundle = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-mortality-roster-bundle.html";

        /// <summary>URL for Mortician</summary>
        public const string Mortician = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-mortician.html";

        /// <summary>URL for PlaceOfInjury</summary>
        public const string PlaceOfInjury = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-place-of-injury.html";

        /// <summary>URL for RecordAxisCauseOfDeath</summary>
        public const string RecordAxisCauseOfDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-record-axis-cause-of-death.html";

        /// <summary>URL for SurgeryDate</summary>
        public const string SurgeryDate = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-surgery-date.html";

        /// <summary>URL for TobaccoUseContributedToDeath</summary>
        public const string TobaccoUseContributedToDeath = "https://hl7.org/fhir/us/vrdr/StructureDefinition-vrdr-tobacco-use-contributed-to-death.html";

    }

}
