name: BFDR Testing

on:
  push:
    branches:
      - main
      - Natality-feature
    paths:
      - 'projects/BFDR/**'
      - 'projects/BFDR.CLI/**'
      - 'projects/BFDR.Messaging/**'
      - 'projects/BFDR.Tests/**'
  pull_request:
    branches:
      - main
      - Natality-feature
    paths:
      - 'projects/BFDR/**'
      - 'projects/BFDR.CLI/**'
      - 'projects/BFDR.Messaging/**'
      - 'projects/BFDR.Tests/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects
    strategy:
      matrix:
        dotnet-version: [2.1.815, 3.1.408, 6.0.100]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore bfdr-dotnet.sln
    - name: Build
      run: dotnet build bfdr-dotnet.sln --configuration Release --no-restore
    - name: Test
      run: ./BFDR.Tests/run_tests.sh