name: Lint commit message

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Validate pull request title with commitlint
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.pull_request.title }}" | commitlint --verbose
      - name: Validate pull request title with commitlint
        if: github.event_name == 'workflow_dispatch'
        run: gh pr view --json title -t "{{.title}}" | commitlint --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}